### ISSUE TITLE
Cleanup the minikube section of the readme...

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/kabanero-operator#110]
Kabanero Foundation is too fat to run in MiniKube/MiniShift even though you can run the operator to develop certain parts of Kabanero in MiniShift.   We need to clarify the README.md section as to what we mean by "installing" the operator in MiniKube.

**Comment by kaczyns** [comment]
Also worth noting that changes in this iteration will use openshift routes, and we'll need to decide how to mange that for someone using Minikube or even just plain Kubernetes.
