### ISSUE TITLE
Need to apply Kabanero landing page when a Kabanero instance is created

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#115]
There is a "welcome to Kabanero" site that needs to be deployed to the namespace where a `Kabanero` instance is created.  To see what this is you can try the following container:
```
docker run -p 9443:9443 --rm alohr51/kabanero-landing:latest
```
This would need to be deployed to the namespace (kubernetes deployment) and then exposed on the SSL port using a service and a route.  It sounds like the container handles its own SSL but I'm not sure.  We can ask @alohr51 if that's true.

It also sounds like the container expects to have a URL where it can point it, set as an environment variable `LANDING_URL`.  When making the pod template in the `Deployment` object there is an `env:` section and we can put an environment variable there.  That would be exposed to the container in the pod, and it could get the URL.  However it's not clear to me if it's possible to create an OpenShift Route to get the URL, before the pod is created.  I am guessing it is possible but I've not tried it.  In this case we'd need to make the route first, then get the URL from the Route status, and then create the deployment.

Once the container is deployed and the URL works from a browser, we'll need to get with @alohr51 and @jgawor to determine how to apply it to the console.  Someone pointed me here, but we need some direction:
https://docs.openshift.com/container-platform/3.11/install_config/web_console_customization.html

**Comment by alohr51** [comment]
Kabanero landing image has been promoted to the Official Kabanero DockerHub https://hub.docker.com/r/kabanero/landing
