### ISSUE TITLE
Discuss the scope of the Appsody operator deployed by the Kabanero operator

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#119]
I'd like to continue the discussion started in #94 about the scoping of the Appsody operator deployed by the Kabanero operator.  Currently for each `Kabanero` object instance, an Appsody operator is deployed in that namespace, which only watches that namespace.  There can only be one `Kabanero` instance per namespace.

@arthurdm @navidsh @kyleschlosser 

Going forward, there is a desire to have the Appsody operator watch multiple namespaces.  I've had conversations with several different people with different opinions so this is really going to be a brain dump which can hopefully evolve into a discussion about how this should look going forward.
1) There is a desire to only deploy the Appsody operator if there are collections in the Kabanero instance that require it.  So for example if there were a Kabanero instance which only contained collections that promote code from dev to test, there would be no need for Appsody in that instance, and therefore the Appsody operator would not be installed there.  I think this was with the understanding that Appsody only watches a single namespace, which is no longer a restriction.
2) There is a desire to have the Appsody operator watch more than one namespace.  My understanding of the next rev of Kabanero is that there will be a Kabanero Instance which contains a new concept called a Workspace, where a workspace is a pair (or more) of Namespaces.  Under this arrangement the Appsody operator would need to watch all of the namespaces contained in all of the Workspaces.  It seems at this point that Appsody should be a cluster scoped operator.  At that point it becomes difficult for the Kabanero operator to manage, since it would need to keep track of whether it installed an Appsody operator to this cluster or not (any Kabanero instance on the cluster might have done it) and coordinate when it's safe to remove the Appsody operator.  It would become a pre-req dependency like Knative and Tekton Pipelines, that is pre-installed on the cluster and is not managed by the Kabanero operator.
3) It was mentioned in #94 that it might be nice to give the user the choice as to what to watch.  I just worry about the operator managing that in an intelligent way, such that we don't deploy two operators that are both watching the same namespace and both trying to react to what is happening there.  Maybe there is no concern here but it seems like a bad idea to me.

**Comment by stephenkinder** [comment]
The Appsody operator managed by Kabanero is owned by the Kabanero operator.  If the consumer wants to expand the scope of the operator to multiple namespaces, they are free to deploy it themselves.   We aren't deploying general use components.  That said, you are dead on with the current design thinking around multi-namespace Workspaces.

**Comment by csantanapr** [comment]
The appsody operator should be deploy once by kabanero on the kabanero namespace but the defect I found is that when customer deploys using kabanero piepeline and configures the appsody application CR on a different namespace appsody operator is not listening on their namespace. 

Appsody operator needs to be configure with the env variable to listen to all namespace this way customer can create appsody application on their namespace

This is how Tekton and Knative operators work they listen on all namespace for custom resources of type Knative and Tekton

**Comment by csantanapr** [comment]
Also istio controller is configured this way to listen to custom resource such as virtualservice and gateway

**Comment by arthurdm** [comment]
hi guys - the Appsody Operator can be configured in different ways, depending on the outcome wanted.  It can watch its own namespace, another namespace, or all namespaces.  The mechanism to control that is outlined [here](https://github.com/appsody/appsody-operator/tree/master/deploy/releases/0.1.0#installation).

It depends on how Champ wants to slice things:  he may want to configure different defaults/overrides for different lines of business - in which case you would want different instances of the operator watching different namespaces - or maybe they just want something consistent across the enterprise - in which case a single instance watching all namespaces would be suitable.

**Comment by kaczyns** [comment]
hi guys - it seems like we've settled (for now) on having the kabanero operator (v0.2.0) take in a list of target namespaces, and then deploying the appsody operator to watch the namespace where kabanero is installed, as well as the target namespaces.  The new version of the appsody operator (0.2.0) includes a cluster role which allows these target namespaces to deploy appsody applications.

Are we comfortable with ending the discussion here for now, or is there still more work to be done?  We've not addressed deploying appsody at the cluster scope, I'll need you to tell me if that's still a requirement.

**Comment by csantanapr** [comment]
Targeting a set of namespace I think it solves the problem. 

My other concern how would this work for adding and removing namespaces being watched?


Meaning when I install kabanero the some target namespaces don’t exist, as new projects come onboard or test namespaces how does the user add namespaces? Is there a config map or CR that I had the list of namespaces being watched the operations person can list, add, remove namespaces ?

**Comment by arthurdm** [comment]
Thanks @kaczyns - it's great that Kabanero will leverage the multi-namespace support.

I agree with @csantanapr's point about updating the namespaces afterwards.  Is there an existing CR that holds the Kabanero install configuration?   That could be the perfect place to edit the list of namespace and then simply `oc apply` it.

**Comment by kaczyns** [comment]
```yaml
apiVersion: kabanero.io/v1alpha1
kind: Kabanero
metadata:
  name: kabanero
spec:
  targetNamespaces:
  - ns1
  - ns2
```
When you change this list (`oc apply` or whatever) we'll re-deploy the Appsody operator deployment with a new watch namespace list.

**Comment by arthurdm** [comment]
that's great @kaczyns, thanks.   I am good with closing this issue.

**Comment by csantanapr** [comment]
Perfect +1

I’m ok if you want to close

**Comment by kaczyns** [comment]
Thanks for the dialog guys.  Please open a new issue if we need to make another enhancement.
