### ISSUE TITLE
Add license scanning to pull request processing

### ISSUE THREAD

**Issue by kyleschlosser** [kabanero-io/kabanero-operator#12]
When a pull request is submitted, one of the prerequisite checks is to scan it for open source license compatibility with our project.

**Comment by stephenkinder** [comment]
Given Kabanero.io is composed of many open source frameworks, does this issue focus only on contributions that the community contributes directly made to the Github Kabanero project?

**Comment by kyleschlosser** [comment]
@stephenkinder this issue was intended for the kubernetes-operator project only
