### ISSUE TITLE
Kabanero install script is failing

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/kabanero-operator#135]
@mtamboli commented on [Wed Aug 28 2019](https://github.com/kabanero-io/docs/issues/61)

Install script "install-kabanero-foundation.sh" need to be updated
1. Please update Kabanero install script  to reflect latest Kabanero release. 
KABANERO_BRANCH="${KABANERO_BRANCH:-0.1.0}

2. Install script was failing with these errors:
```
the namespace from the provided object "knative-sources" does not match the namespace "kabanero". You must pass '--namespace=knative-sources' to perform this operation.
the namespace from the provided object "knative-sources" does not match the namespace "kabanero". You must pass '--namespace=knative-sources' to perform this operation.
the namespace from the provided object "knative-sources" does not match the namespace "kabanero". You must pass '--namespace=knative-sources' to perform this operation.
unable to recognize "https://github.com/kabanero-io/kabanero-operator/releases/download/0.1.0/kabanero-operators.yaml": no matches for kind "Config" in version "operator.tekton.dev/v1alpha1"
```
To workaround above issue, had to remove -n Kabanero from the following command:
  `oc apply -n kabanero-f https://github.com/kabanero-io/kabanero-operator/releases/download/0.1.0/kabanero-operators.yaml`

 oc get pods
```
NAME                                           READY     STATUS    RESTARTS   AGE
kabanero-operator-bf65d8b85-4rfr7              1/1       Running   0          2h
knative-eventing-operator-67cdf5dc9f-fntk6     1/1       Running   0          2h
knative-serving-operator-b64558bbc-blsnq       1/1       Running   0          2h
openshift-pipelines-operator-cfc786cc7-tnkvz   1/1       Running   0          2h
tekton-dashboard-66788444c8-8vh2r              1/1       Running   0          1h
webhooks-extension-d7b4745d6-9tlcx             1/1       Running   0          1h
```

**Comment by stephenkinder** [comment]
@dacleyra I consulted with the Tekton Dashboard team, their recommended levels are:

1. Tekton 0.5.2
1. Tekton Dashboard and Dashboard Extension -- 0.1.1
1. Knative Serving, Eventing -- 0.6.0
1. Istio -- 1.1.7

**Comment by stephenkinder** [comment]
@mtamboli Dan will update the releases and versions.  This addresses bullet 1 and I believe it will also address bullet 3 (https).  
 bullet 2 - I am not familiar with the namespace issue -- if there isn't already an issue opened for this, please open a separate one.
bullet 4 -- please open a separate issue on this -- that said, the install scripts are pointed to from the website, so please indicate that complexity in the new issue.
bullet 5 --the cli microservice, landing page and operator already installed by kabanero -- if there is a problem or new function -- please open a new issue.

**Comment by mtamboli** [comment]
We had a discussion on a issue in the slack channel where workaround was to update the namespace from tekton-pipelines to kabanero. Assuming this change will be taken care in the install script. So not opening a new issue?

kubectl get ksvc webhooks-extension-sink -o yaml -n kabanero | grep -A2 INSTALLED_NAMESPACE

**Comment by marikaj123** [comment]
According to Steve, closing
