### ISSUE TITLE
automatically create AESEncryption key secret

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-operator#136]
Currently the command-line-service pod generates a random secret at startup. The key is used to sign the JWT and the Github PAT or Password. If the pod is restarted the secret will change and all encrypted artifacts will be invalid.
That will cause confusion to Todd when useing the CLI since he will be logged out and we may not handle that case smoothly

see: https://github.com/kabanero-io/kabanero-security/wiki/Setting-up-the-CLI-backend-app#configure-aes-encryption-key

Best solution is for Kabanero Operator to create the random number based secret per Kabanero instance.

**Comment by kaczyns** [comment]
This should be done concurrently with #138

**Comment by kaczyns** [comment]
This was fixed in #170.
