### ISSUE TITLE
Enable travis builds for this project

### ISSUE THREAD

**Issue by kyleschlosser** [kabanero-io/kabanero-operator#15]
Enable travis ci builds for this project. 

Work to be completed: 

- [ ] Enable travis in a fork by visiting travis-ci.org, in the upper right corner by your username, click settings, then click the 'enable' check for kabanero-operator
- [ ] Work through any build failures, committing to the fork, and observing the build results
- [ ] Enable travis for github.com/kabanero-io/kabanero-operator (awaiting authorization)

**Comment by kyleschlosser** [comment]
Waiting on authorization

**Comment by stevenschader** [comment]
https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps
looks like travis-ci.com is the goto location ( not travis-ci.org )
