### ISSUE TITLE
Resolve publishing of dependencies of Kabanero Operator to OperatorHub 

### ISSUE THREAD

**Issue by kyleschlosser** [kabanero-io/kabanero-operator#16]
Some of the dependent operators are not published to OperatorHub. We have several options:
 
* Wait for the dependencies to arrive
* Embed the dependencies into the Kabanero Operator
* Fork and publish the dependencies

**Comment by kaczyns** [comment]
Some notes about what I've found so far:
1) Istio is available on operatorhub.io but not the Open Shift catalog.
2) knative-serving pre-reqs Istio (but the operator CSV does not require it, which is odd), and it's available only in the Open Shift catalog (which may be why the CSV doesn't require it)
3) knative-eventing is only available in the Open Shift catalog
4) openshift-pipelines is only available in the Open Shift catalog

So I guess a summary is all the requirements for Kabanero are in the Open Shift catalog, except that the requirements of the requirements are in the Operatorhub.io catalog.

**Comment by kyleschlosser** [comment]
The immediate plan is to publish into the OpenShift catalog.
