### ISSUE TITLE
validate CollectionID so it doesn't break Pipeline variable substitution

### ISSUE THREAD

**Issue by tseelbach** [kabanero-io/kabanero-operator#167]
See https://github.com/kabanero-io/kabanero-operator/issues/114#issuecomment-528899461
Since the CollectionId is being used  as a substitution/variable in the Pipelines we need to validate / restrict the field so that pipelines don't fail with invalid characters.

**Comment by kaczyns** [comment]
@tseelbach It seems like this validation should be done when the collection is generated.  By the time the operator gets it, there is nothing that we can do other than fail the Collection activation.  Do you agree?
