### ISSUE TITLE
Warn on collection activation when the resultant pipeline name is in use by another collection.

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/kabanero-operator#169]
Given the current need for the operator to manage unique pipeline names for each active collection, the operator should at least issue a warning or give an error status for collections activated that result in pipeline names that are in use by another collection.

**Comment by kaczyns** [comment]
@stephenkinder Can you say more about which specific cases you'd like to see an error generated for?  It's difficult for the operator to know when there is a conflict (at least currently) because on a collection re-activation, the pipeline is going to already be there, but we don't know that it's there because this collection activated it previously.  Are you concerned about cases where the name mangling generates the same name twice?  Or something else?

**Comment by stephenkinder** [comment]
Just the simple case that the java-microprofile and node.js collection have the same pipeline name.  If we have a limitation that collections must have unique resultant pipeline names, then we need to fail the activation of a pipeline that already exists and bound to another collection.  

The default collections use the new Kabanero symbolic substitution for collectionId, but the enterprise architect may make a mistake in his collection curation. 

The collection build may not be able to determine if there is a conflict during build time, the operator is the only one seeing the real resultant pipeline names in this given cluster.

It is not an error to reactative the same pipeline for a collection reactivation; it is only a conflict if there are two active collections that have the same pipeline name.

**Comment by kaczyns** [comment]
I think the way we have to solve this problem, is to annotate the collection artifacts (what we read and apply out of the pipeline zip) with the sha256 of the pipeline zip.  Then subsequent activation, either for a different version of the same collection, or a different collection, if that artifact already exists, but the sha256 in the annotation does not match the sha256 of the pipeline we are currently activating, then we issue an error or a warning.

Consider this situation - Champ is using version 0.2.5 and 0.2.10 of java-microprofile collection.  These two versions use different pipeline zips, but the artifacts within use the same name (ie CollectionId-build-task).  When we create the `java-microprofile-build-task` for version 0.2.5, we should annotate it `kabanero.io/sha256: a7f983a5b321....` with the sha256 of the pipeline zip.  Then when we activate version 0.2.10 we'll see that there is already a `java-microprofile-build-task` created, so we'll compare the annotated sha256 with the sha256 of the pipeline zip for version 0.2.10.  They will be different, so we issue a warning, and then, ????  I guess today we apply it anyway.  This issue says warn, so lets continue to go with that for now.  We can change the behavior to fail later if we need to.

I think a manifestival transform can probably be used to apply the annotation with the sha256 in it.

**Comment by kaczyns** [comment]
We've added support to use the pipeline digest as a fill-in for pipeline names.  We also support multiple stacks using the same pipelines (affectionately referred to as "the operator learned to count").  I believe that this fulfills this requirement.  Please re-open the issue if you don't agree.
