### ISSUE TITLE
disable finalizers to have a clean uninstall for the kabanero

### ISSUE THREAD

**Issue by tam512** [kabanero-io/kabanero-operator#175]
If uninstall Kabanero in OpenShift what has webhooks, the uninstall will be hung at `Uninstall Kabanero Enterprise Operator...`

The current workaround is to remove finalizers in `githubsources.sources.eventing.knative.dev` and `routes.serving.knative.dev`

- check for the existing of githubsources.sources.eventing.knative.dev or routes.serving.knative.dev in kabanero project
```
$ oc get all
NAME                                                                                        READY     REASON
clusteringress.networking.internal.knative.dev/route-579585dd-d0ec-11e9-9988-e2e5adbc84b6   True      
Tams-MBP:HelloWorldNodejsExpress tam$ oc project kabanero 
Now using project "kabanero" on server "https://c100-e.us-south.containers.cloud.ibm.com:31467".
Tams-MBP:HelloWorldNodejsExpress tam$ oc get all
NAME                                                                                        READY     REASON
clusteringress.networking.internal.knative.dev/route-579585dd-d0ec-11e9-9988-e2e5adbc84b6   True      

NAME                                                         URL                                                                                                                                    READY     REASON
route.serving.knative.dev/tamd-njsexpress-helloworld-zbfwb   http://tamd-njsexpress-helloworld-zbfwb.kabanero.ocp-svt-3-4c666281ea4dfbebe4821a4891d29f22-0001.us-south.containers.appdomain.cloud   True      

NAME                                                                   AGE
githubsource.sources.eventing.knative.dev/tamd-njsexpress-helloworld   1d
```
and remove the finalizers (_remove the below_) 
```
finalizers:
  - github-source-controller
```
using command

`OC_EDITOR=nano oc edit githubsources.sources.eventing.knative.dev <name>`
`OC_EDITOR=nano oc edit routes.serving.knative.dev <name>`

**Comment by kaczyns** [comment]
Removing finalizers is not good practice because the finalizer serves a purpose which is negated when the finalizer is removed.  We should investigate why the finalizer is not running.  

What process are you using to uninstall Kabanero?

**Comment by mtamboli** [comment]
@kaczyns We need a good fix for the uninstall to work when webhooks exists. This is how I was initiating uninstall.
docker run -v ~/.kube:/root/.kube:z -u 0 -t -v $PWD/data:/installer/data:z  -e LICENSE=accept -e ENTITLED_REGISTRY -e ENTITLED_REGISTRY_USER -e ENTITLED_REGISTRY_KEY "$ENTITLED_REGISTRY/icpa/icpa-installer" uninstall --skip-tags ghe

**Comment by tam512** [comment]
I uninstalled with command

`docker run -v ~/.kube:/root/.kube:z -u 0 -v $PWD/data:/installer/data:z -e ENTITLED_REGISTRY -e ENTITLED_REGISTRY_USER -e ENTITLED_REGISTRY_KEY -e LICENSE=accept "$ENTITLED_REGISTRY/icpa/icpa-installer" uninstall`

**Comment by kaczyns** [comment]
I am sorry that you are having trouble removing Kabanero from this system.  I don't think that it's appropriate for this issue to be opened against the operator at this time.  The operator doesn't have an uninstall process or hook, and so it's not appropriate for the operator to be scanning for finalizers before the operator is removed.  Further, it's not appropriate for the Kabanero operator to be removing finalizers that were created by Knative.

I would suggest that you consider the uninstall process that you are using to remove Kabanero.  Maybe the objects can be removed in a different order to prevent this hang from occurring?

To investigate the finalizer would require more work, and it's probably more appropriate to open an issue against Knative.
