### ISSUE TITLE
Introduce version lifecycle management into the operator

### ISSUE THREAD

**Issue by kyleschlosser** [kabanero-io/kabanero-operator#176]
Traditionally, a Kubernetes operator uses an independent lifecycle from the software it manages. This creates scope of impact for upgrades so that upgrading the operator does not adversely impact the software instances, and a single software instance can be upgraded or downgraded without impacting the other software instances. 

The Kabanero operator does not adhere to this principal at the moment. Upgrading the operator may cause software instances to be upgraded because we only have a single static orchestration built into the operator. 

This epic proposes respecting the version identifier provided by the user in the Kabanero resource kind, introducing per version orchestrations, and consolidating the management of versions into human editable configuration files.

**Comment by kaczyns** [comment]
This was resolved by PR #184
