### ISSUE TITLE
When reading a collection archive, use manifest.yaml and signature check

### ISSUE THREAD

**Issue by dacleyra** [kabanero-io/kabanero-operator#183]
Technical Debt

When reading a collection archive, 
The signature of the archive should be checked against the index.yaml
The manifest.yaml should be used
The file signatures should be checked against the manifest.yaml

https://github.com/kabanero-io/kabanero-operator/blob/master/pkg/controller/collection/archive.go#L27

**Comment by dacleyra** [comment]
Code is ready. Deliver after collection v0.1.2+ which corrects the sha256-signatures
https://github.com/kabanero-io/collections/commit/25813a5afe4acb7b6d7fd969711fdf78e152539e

**Comment by kaczyns** [comment]
This is fixed by #194
