### ISSUE TITLE
Expose JwtExpiration as environment variable via configMap

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-operator#188]
Expose JwtExpiration as environment variable via configMap

Add JwtExpiration as a number of minutes to configmap and env var via Kabanero Document

**Comment by kaczyns** [comment]
@davco01a @brutif We should have a conversation about where this belongs in the Kabanero document.  The things we've added so far were directly related to our interaction with Github, and so they were in a `Github:` section of the Kabanero document.  How do we explain to the user what this is?  I am guessing they are not going to know what `JwtExpiration` is or how it affects what they are doing.  I'm assuming that this is the amount of time that a user's session with the CLI will remain until they have to log in again.  Do you have a recommendation as to how we can add this to the Kabanero document in a way that the user will understand?

**Comment by davco01a** [comment]
KabaneroCLILoginExpiration may be a better name

**Comment by davco01a** [comment]
Agree that this is broader than just github, but documenting shouldn't be too hard, we just have to find a suitable spot in the Kabanero document

**Comment by brutif** [comment]
@kaczyns @davco01a can you point me to the document please?

**Comment by kaczyns** [comment]
@brutif the document @davco01a is referring to is the Kabanero CRD:
https://raw.githubusercontent.com/kabanero-io/kabanero-operator/master/deploy/crds/kabanero_kabanero_crd.yaml

There are several `spec:` sections - the section that has `properties:` and then `github:` is the one we are referring to.  There is a `cliServices:` section that was recently added, maybe that's where this goes.  Something like `spec.cliServices.sessionExpirationMinutes` maybe....

**Comment by brutif** [comment]
@kaczyns thanks.  I was looking at https://github.com/kabanero-io/docs/blob/master/ref/general/installing-kabanero-foundation.adoc and not seeing anything about editing any kind of config file, which might still be a gap. Whatever you and @davco01a think is a good name is fine, adding detection of the environment variable to the app is trivial once we know it's name.

**Comment by davco01a** [comment]
`cliServices.sessionExpirationMinutes` sounds good to me

**Comment by davco01a** [comment]
we'll need to get this into into:  https://github.com/kabanero-io/docs/issues/66

**Comment by davco01a** [comment]
directly into env var is fine

**Comment by dacleyra** [comment]
closing, resolved by https://github.com/kabanero-io/kabanero-operator/pull/213
