### ISSUE TITLE
Compile the operator for POWER architecture

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#189]
See https://github.com/kabanero-io/kabanero-foundation/issues/66
I think this means we need to either have a 2nd Travis build that runs on power, or, have some other manual way of building and pushing the same image compiled on power.

**Comment by dacleyra** [comment]
travis-ci does not have multi-arch workers (except experimental arm)

We can use qemu to produce builds for each arch, with a fat manifest push for the docker images

article:
https://developer.ibm.com/linuxonpower/2017/07/28/travis-multi-architecture-ci-workflow/

example:
https://github.com/lwolf/docker-multiarch

**Comment by kaczyns** [comment]
This is superseded by #547
