### ISSUE TITLE
implement multiple namespace support in the Kabanero Operator

### ISSUE THREAD

**Issue by tseelbach** [kabanero-io/kabanero-operator#196]
Under the current design, a Kabanero instance is associated with the namespace in which the Kabanero resource is created. Note that although our examples may place the Kabanero resource into the namespace kabanero this is unnecessary, the Kabanero resource can go into any valid namespace within the cluster. This design means that Appsody and KAppNav are both associated only to the namespace that hosts the Kabanero instance and collections, however, it's common for applications developed through Kabanero to be deployed into other namespaces.
Add the ability for Kabanero to be hosted in one namespace (the meta/namespace associated with the Kabanero instance resource) but additionally watch for applications in other namespaces. The additional namespaces are expressed in the Kabanero resource like this:

apiVersion: kabanero.io/v1alpha1
kind: Kabanero
metadata:
  name: kabanero
spec:

  targetNamespaces:
  - ns1
  - ns2

**Comment by kaczyns** [comment]
PR #190 works fine, but appsody-operator 0.1.0 does not support a list of namespaces to watch.  I tested with `daily` and that works.  We have to wait for the next release of the appsody-operator before we can complete this work.  @leochr says there will be a new named release by Monday Sept 30 so we should be able to pull that in and merge PR #190 at that point.

**Comment by marikaj123** [comment]
Waiting for Apssody operator to be cut.

**Comment by kaczyns** [comment]
This was delivered in #190
