### ISSUE TITLE
Kabanero operator managed Che

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/kabanero-operator#197]
This issue represents the work to include the Che open source project as part of the Kabanero foundation.  The Kabanero project has a specific "Kabanero customized" Che container, managed in the kabanero-io Github: https://github.com/kabanero-io/kabanero-che.

The Che feature will be installed in the Kabanero instance namespace if the Kabanero CRD contains the Che configuration stanza; otherwise, Che is not installed.  The CRD extension will look similar to: 

```apiVersion: kabanero.io/v1alpha1
kind: Kabanero
metadata:
  name: kabanero
spec:
  che:

    # Overrides the platform wide settings for version on this component
    version: "7.0.0"

    # Overrides the image as a separate repository or tag
    repository: quay.io/eclipse/che-operator
    tag: "7.0.0"

    # Overrides the image uri
    image: quay.io/eclipse/che-operator:7.0.0
```

We are still discussing the pros and cons of adding an `enabled=true` flag and whether the default should be `true` or `false`.

**Comment by kaczyns** [comment]
We are waiting for the Che team to upload the `kabanero-che` image to kabanero dockerhub

**Comment by kaczyns** [comment]
This was delivered in #209
