### ISSUE TITLE
Discuss exposing cliservice.image tag as an environment variable

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-operator#202]
Discuss expose `cliService.image` tag as an environment variable

**Comment by davco01a** [comment]
@kaczyns Said, "I think it would be better, if your build writes a properties file, or something like that, that you can read"

Let's discuss the pros and cons of using a property file vs. just deriving the version by parsing the release tag from the image tag in the CRD (if it were an env var)

**Comment by davco01a** [comment]
@kaczyns also says, "so what are you going to do, if someone copies the image out of kabanero dockerhub into their own private repository, and uses that instead?  how will you know what version of the microservice you have?"

**Comment by stephenkinder** [comment]
@davco01a if you want a build version burned into the image, you should do so during the build; as an example, one could build the specific containers and tag them with releases, but if you must burn in a "release", the collections repo triggers a Travis build based on its collection build/tag which could be leveraged to extract the release...  there are probably many common open source patterns for doing so.

**Comment by stephenkinder** [comment]
I've marked this question in-progress, with @davco01a driving the discussion; if this comes a work item, we can put back in the backlog and prioritize with the other work the CLI squad has.

**Comment by kaczyns** [comment]
@davco01a could you please re-state the problem that you are trying to solve?  I think it got lost in the opening dialog that we had outside of this issue.  The operator can expose the image name as an environment variable, but I don't think that it solves the problem that you're trying to solve (that I remember from our conversations).

**Comment by kaczyns** [comment]
I am going to close this issue for now with the recommendation of using `TRAVIS_TAG` or some other method at build-time of encoding the version of the CLI service into the CLI service itself.  This allows you to know what version you have, even if someone copies and renames the image to another registry and/or uses a different tag.

Please re-open the issue if you feel like you still need the Kab operator to expose something to you via environment variable.  Thanks!
