### ISSUE TITLE
Add kappnav component to the Kabanero must-gather script.

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/kabanero-operator#208]
Now that the kabanero-foundation is managing a kappnav deployment, we should add kappnav component must-gather to the kabanero-foundation must-gather scripts.

**Comment by kaczyns** [comment]
@cvignola @rlcundiff Do you have any suggestions as to what we should gather here?  By default we're going to gather pod logs for anything in the `kappnav` namespace, and any object yamls that are created by the installation (roles, service accounts, deployment, etc).

**Comment by rlcundiff** [comment]
That sounds good and I don't have anything else to suggest.  As we gain experience with the issues users encounter we may find other things to add in future releases.

**Comment by kaczyns** [comment]
This was shipped in kabanero-io/kabanero-foundation#90
