### ISSUE TITLE
Operator does not re-apply certain collections automatically when they are removed

### ISSUE THREAD

**Issue by smcclem** [kabanero-io/kabanero-operator#216]
**Describe the bug**
When using the oc command to remove a collection, the operator does not automatically re-apply the collection that was removed:

java-microprofile  - This collection seems to re-apply correctly.

java-spring-boot2, nodejs , nodejs-express and nodejs-loopback  do not. 

**To Reproduce**
run :  oc delete collection java-spring-boot2
The collection will delete, then run oc get collection java-spring-boot2 and it will not be re-activated later on. 

Operator does not re-apply certain collections automatically when they are removed

**Comment by kaczyns** [comment]
This is related to #99 - at first I thought #99 was complete since deleting the microprofile collection results in it being re-created, but then apparently we're not watching the other four collections.
