### ISSUE TITLE
Can't deploy landing page on OCP 4.2

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#228]
```
"Error deploying the kabanero landing page.","Request.Namespace":"kabanero","Request.Name":"kabanero","error":"configmaps \"webconsole-config\" not found"
```
Technically the pod is deployed fine, but the next step, updating the OKD console, does not work on 4.2.

**Comment by stephenkinder** [comment]
@kaczyns So I've pinned this issue has high priority as a triage activity.  We need to understand if OCP extensions have vanished, if there is a replacement, or if this is just a bug in the OCP 4.2 environment.

**Comment by kaczyns** [comment]
I spent some time in the documentation for OCP and the pages describing how to extend the console are gone.

I also spent some time in github.com/openshift/console but didn't see any instructions there.

I'm sure it's possible but someone is going to have to dig into it.

**Comment by kaczyns** [comment]
@alohr51 @jgawor Do either of you have some time to investigate the proper way to "alter" the OpenShift console on 4.x?  I think one or both of you implemented the original extension on 3.x.  @mezarin found some clues but it's not really enough to go on.

**Comment by mezarin** [comment]
@kaczyns this the only link i found that talks about console extensions on 4.X: https://blog.openshift.com/wp-content/uploads/OpenShift-4-Roadmap-Update-William-Markito-and-Chris-Blum.pdf (EXTENDING THE CONSOLE).

**Comment by kaczyns** [comment]
Clues:
https://github.com/openshift/console-operator/blob/master/pkg/console/subresource/consoleserver/types.go
https://github.com/openshift/console-operator/blob/master/manifests/00-crd-operator-config.yaml

Not sure what all of this means... it looks like the branding schema validation is hard-coded... not sure if we can contribute our own (looks like AWS has its own value...)

**Comment by kaczyns** [comment]
This is the PR where the Azure customization was done.
openshift/console#1233
It looks like there are a couple of other associated PRs in other areas (API, operator)

**Comment by marikaj123** [comment]
Need help for a new resource to look after this issue.

**Comment by kaczyns** [comment]
Thanks to @cvignola for pointing me to these new instructions for OCP 4.2:
https://docs.openshift.com/container-platform/4.2/web-console/customizing-the-web-console.html#creating-custom-links_customizing-web-console

It seems like we may need to do some re-arranging.  @alohr51 @jgawor FYI.

**Comment by kaczyns** [comment]
Chris and I spoke about the console "real estate"... kAppNav will support `okdAppLauncher` and the Kabanero operator should set it when it deploys kAppNav 0.1.2 in Kabanero 0.3.0.  We are not sure what to do about `okdFeaturedApp` yet but we can continue to set it to `false` in Kabanero for now.

**Comment by alohr51** [comment]
@kaczyns I belive the goal is for the landing page to be deployed at a cluster level. Whether that affects this work or not, I'm not sure, but I wanted to make sure that is known.

From what I saw it seems cluster level things are installed via the installation script (not the operator) is that correct? I assume we will still need these extension details regardless though.

**Comment by kaczyns** [comment]
Thanks @alohr51 - yes I believe we have an issue open to move the landing page to the cluster scope.  It will be impossible to (or I guess more correctly, I would be uncomfortable) update the OCP console from the shell script, both install and uninstall.  As these Kabanero cluster-level dependencies keep cropping up, we need a cluster-level operator (CRD) that can process these.  Some thought needs to be put into how this can happen and it probably will not happen in release 0.3.0.

**Comment by alohr51** [comment]
@kaczyns I gave the link above about customizing the web console a quick read and it looks like the solution is all about defining some CRD's to customize the web console. From what I read is doesn't look like the application code for the landing page would need to change at all.

Is defining these CRDs (like the ConsoleLink CRD) something the operator would do? I just want to make sure the landing page code won't need to adapt.

**Comment by kaczyns** [comment]
@alohr51 yes the kab operator would create the CR instances, but it would be helpful if you could help us figure out what pieces go where.  For example, they want a `.png` file for the customization logo... today I think we modify the console with some `.js`. and a `.css` file.  Does the landing page provide a `.png` that we can use?  Also, if you have an opinion on which of the existing links should go on which parts of the page, that would be helpful.

**Comment by alohr51** [comment]
@kaczyns so currently we use this gray kabanero logo for the customization - you can use the URL `<LANDING_PAGE_URL>/img/gray-kabanero-logo.png` and the text I think is in the CRD and would just be "Kabanero"

Can you expand on the last part? which existing links and which page?

**Comment by kaczyns** [comment]
@alohr51 We had the following customization URLs in OKD 3.11:
```
		"LANDING_URL/appnav/openshift/featuredApp.js",
		"LANDING_URL/appnav/openshift/appLauncher.js",
		"LANDING_URL/appnav/openshift/projectNavigation.js",
```
I navigated to each of these and I see now that they all return the same base URL which basically links to the landing page index.  We'll just use that.  I'm sorry for the confusion.
