### ISSUE TITLE
Support deactivating a collection that is still in the CollectionHub

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#229]
See kabanero-io/kabanero-foundation#85.  The operator needs to support the activation and deactivation of collections via a new attribute in the `kind: Collection`.  I am proposing the following YAML:
```yaml
apiVersion: kabanero.io/v1alpha1
kind: Collection
metadata:
  name: java-microprofile
spec:
  version: 0.0.2
  desiredState: active
```
where `desiredState` is new, and the valid choices are active or inactive.  If the collection controller comes across one which does not have this parameter set, it should default to `active`.  It would be nice to use the `kind: Kabanero` in the same namespace and read the `activateDefaultCollections` attribute to get the default value, but it may not be easy to figure out which repository to use if there is more than one.

The kabanero controller should change to always create `Collection` instances when it reads the repository.  The initial value of `desiredState` should be the value of `activateDefaultCollections`.

The collection controller should change to only activate a collection if the `desiredState` is `active`.  It needs to record the state somewhere in the status area if it's not already recorded.  If the `desiredState` changes to `inactive`, and the status indicates that it is currently active, it should be deactivated (the pipeline YAMLs should be destroyed).  It should remain in that state until the `desiredState` is changed back to `active`.

**Comment by kaczyns** [comment]
If `desiredState` gets set to something else (like `fred`) we should print an error message in the `status` section and just remain in whatever state we were in previously.

**Comment by davco01a** [comment]
Is the CLI supposed to set these to desiredState: active ( REFRESH )

or desiredState: inactive ( DEACTIVATE )

**Comment by mezarin** [comment]
My understanding is that the Kabanero CLI would need to set those state values as you describe.

Note that REFRESH does equate to a collection's active desired state per the description of the REFRESH command. REFRESH has an overloaded meaning as it can be used to: "refresh the list of collections from master" and "restore deactivated collections". 

From an operator point of view, if a particular collection is deactivated, you would set the desired state to activate to enable it again.

**Comment by davco01a** [comment]
so on Kab CLI refresh we would scan the list in the curated collection and it's not active then we'd change the desiredState to active

Also if we scanned the curated collection and saw that a collection was not there anymore, we would change it's desiredState to inactive, this might eliminate the need for deactivate if @ralanlittle approves of an automated deactivate on REFRESH

**Comment by kaczyns** [comment]
I think we need to come to an agreement on what the behavior is.  I think that a `deactivate` is pretty clear - the behavior should change from deleting the `Collection` instance (0.2.0) to changing the `desiredState` to `inactive` (0.3.0).

I agree that `refresh` needs to be discussed, I see that you set up a meeting to do that next week.  I don't think that changing the state from `inactive` to `active` on a refresh is a good idea, because if Todd deactivated a collection, he wouldn't want it to be re-activated on a refresh (maybe it's supposed to be deactivated).  The previous model of `activate` and `deactivate` made more sense to me.  I guess we'll hash it out next week.
