### ISSUE TITLE
Update operator to inject liveliness probe into Deployment YAML for CLI Service

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-operator#231]
Update operator to inject liveliness probe into Deployment YAML for CLI Service

**Comment by davco01a** [comment]
see: https://github.com/kabanero-io/kabanero-command-line-services/issues/70

**Comment by marikaj123** [comment]
@davco01a - Since there is no assignee yet, is this issue going to be delivered in v0.3.0?

**Comment by kaczyns** [comment]
I am closing this in favor or #268.  Please let me know if this issue is still needed.
