### ISSUE TITLE
Creating Kabanero instance using OpenShift Console CRDs does not work correctly

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-operator#235]
Since new Kabanero install does not create instance.  I wanted to create using console.

OKD Cluster Console -> Administration -> CRDS -> Kabanero -> Create Kabanero
You get below yaml file and I click on create to create the default instance. I assumed this is equivalent to using default.yaml from operator sample.
```
piVersion: kabanero.io/v1alpha1
kind: Kabanero
metadata:
  name: example
  namespace: default
spec: {}
```

This creates a sample with below snippet which his not correct:
```
apiVersion: kabanero.io/v1alpha1
kind: Kabanero
metadata:
  creationTimestamp: '2019-10-11T21:06:44Z'
  finalizers:
    - kabanero.io.kabanero-operator
  generation: 2
  name: example
  namespace: default
  resourceVersion: '35948'
  selfLink: /apis/kabanero.io/v1alpha1/namespaces/default/kabaneros/example
  uid: 07c86c64-ec6b-11e9-bc12-0016ac1021d4
spec:
  appsodyOperator: {}
  che:
    cheOperator: {}
    cheOperatorInstance: {}
    enable: false
    kabaneroChe: {}
  cliServices: {}
  collections: {}
  github: {}
  landing: {}
  tekton: {}
```

**Comment by kaczyns** [comment]
Hi @mtamboli - the template that allows us to pre-populate the `Kabanero` CR instance in the console the way you are doing it, is provided in the `ClusterServiceVersion` object when using OLM to install the operator.  There is no way for us to influence what goes there without using OLM.

We have plans to move to OLM in the next release.  In the meantime, the customer will have to use our sample YAMLs as a base to create their own when using the OKD console (or OpenShift console).

**Comment by gecock** [comment]
Hey @kaczyns, is there an epic already for this future work? I don't want this to be closed and lost only to have someone else open a bug on this same issue in the future.

**Comment by kaczyns** [comment]
@gecock #95 had been tracking the OLM work but it's likely we will not submit to community-operators now.  kabanero-io/roadmap#91 is tracking the overall work to get to OCP 4.2 and OLM.

**Comment by mtamboli** [comment]
@dacleyra please take a look if this is possible.

**Comment by dacleyra** [comment]
Navigating CRDSs via 

`Administration -> CRDS -> Kabanero -> Create Kabanero`

or any other CRD, will produce a blank spec. A blank spec is not necessarily valid for any CRD.



To get a default populated Kabanero instance, you need to navigate through the Operator interface

`https://console-openshift-console/k8s/ns/kabanero/operators.coreos.com~v1alpha1~ClusterServiceVersion/kabanero-operator.v0.4.0/kabanero.io~v1alpha1~Kabanero`

`Operators > Installed Operator > Kabanero > Create Kabanero`

**Comment by mtamboli** [comment]
I tried creating instance using above steps in console and it works. IT creates default Kabanero instance as expected so closing this defect.

**Comment by marikaj123** [comment]
@mtamboli - Please close the defect when you are ready. Thank you.
