### ISSUE TITLE
Operator to accommodate new triggers: section in kabanero-index.yaml

### ISSUE THREAD

**Issue by mchenggit** [kabanero-io/kabanero-operator#238]
We are adding a new section to kabanero-index.yaml called triggers. It should not break the operator both server side, and command-line client side. The new section looks like:
triggers:
- description: triggers for this collection
   url: https://github.com/kabanero-io/collections/releases/download/0.2.0/incubator.common.trigger.default.tar.gz 
stacks:
...

**Comment by kaczyns** [comment]
Hi @mchenggit - can you please remind me, does the kabanero-operator need to do anything with this extra information?  Will you be opening up the kabanero-index.yaml yourself (in the webhook) and reading the information, or do you need the operator to copy the information to the `status` section of the individual collections?

**Comment by mchenggit** [comment]
We don't need an update to the CRD instance.  However, we do need to open the files in the trigger directory to read them. If you already read and cache the directory in the file system, we would like to know the location. If you have helper APIs to do this, we'll call them. Otherwise, we'll have to write new code to download and read the directory from within the webhook.

**Comment by kaczyns** [comment]
We are not caching anything yet.  We have #147 where we intend to cache some things, but that's most likely going to be in our local file system and so it won't help you out unless the operator exposes some service that you can call to retrieve the cached information.

**Comment by kaczyns** [comment]
I am going to close this issue, it doesn't sound like the operator has any changes required for reading the triggers from the collection.
