### ISSUE TITLE
Update to operator CRD for triggers

### ISSUE THREAD

**Issue by mchenggit** [kabanero-io/kabanero-operator#239]
Note: This is run-at for 19.21.

Update operator collection CRD to track webhook and secrets. 
1) Create a new default webhook secret on Kabanero instance creation
apiVersion: v1
kind: Secret
metadata:
  name: default-webhook-secret
type: Opaque
data:
  secret: MWYyZDFlMmU2N2Rm

2) Update CRD to track webhook URLs and secrets. For example:
webhooks:
  - type: github
    url: https://github.com/owner/repo
  - type: github
     url: https://github.com/org
     secret: my-other-secret
  - type: docker
     url: ...

**Comment by marikaj123** [comment]
@kaczyns - Is the work for this issue continue to be targeted for v0.3.0 release?

**Comment by kaczyns** [comment]
@marikaj123 Michael indicated this was a "run-at" and so I have not prioritized the work for 0.3.0.  If he comes back and says he needs it, we can try our best to make the updates that he needs.

**Comment by mchenggit** [comment]
Recommend we target secret management for 0.4.  It's too late for Kabanero webhook to leverage the secret in 0.3.

**Comment by kaczyns** [comment]
I spoke briefly with @mchenggit.  I am going to remove this from the 0.4.0 release for now.

**Comment by kaczyns** [comment]
@mchenggit I was unsure if this issue was still valid.  Could you please close it if you no longer require these updates?

**Comment by mchenggit** [comment]
We don't need this any longer due to recent re-design.
