### ISSUE TITLE
manifestival needs to work with vfs

### ISSUE THREAD

**Issue by dacleyra** [kabanero-io/kabanero-operator#24]
manifestival needs to be able to access the vfs that contains 
`config/reconciler/knative-eventing`
`config/reconciler/knative-serving`

until so, workaround by copying `config` to the filesystem using an additional Dockerfile & docker build

**Comment by dacleyra** [comment]
@kyleschlosser 

Commit that adds a func to process an http.FileSystem so we can pass in the VFS

https://github.com/dacleyra/manifestival/commit/1f36e6856f23c07d75e7514b3724f34c2261478c

Let me know what you think

**Comment by kyleschlosser** [comment]
@dacleyra I think the simplest fix is that if the manifestival library supports a custom http Client, we can then use a custom roundtripper. 

Here's an example Roundtripper from the `http` docs: 

```
t := &http.Transport{}
t.RegisterProtocol("file", http.NewFileTransport(http.Dir("/")))
c := &http.Client{Transport: t}
res, err := c.Get("file:///etc/passwd")
```

http.Dir("/) and our VFS implementation are both http.FileSystem objects

**Comment by kaczyns** [comment]
@dacleyra would you mind checking to see if this issue is still valid?  Kyle forked Manifestival and I think he added code that allows Manifestival to read from the vfs.  If it's fixed, can we remove the build work-around?
