### ISSUE TITLE
Installing Kabanero Foundation does not reliably setup the Appsody Tekton pipelines and tasks

### ISSUE THREAD

**Issue by ghodgkinson** [kabanero-io/kabanero-operator#249]
Desired behaviour:

Running the Kabanero Foundation install on OpenShift 3.11 results in the full set of Appsody pipelines and tasks being created (in addition to the rest of the Kabanero).

Actual behaviour:

Running the install does not give a consistent result. Sometimes it results in no pipelines and tasks being created. Sometimes it results in a few pipelines created and no tasks. Sometimes it results in a few pipelines and a few tasks.

Additional information:

I ran the install multiple times (with the uninstall in between) before I got a few pipelines and tasks installed. I did not notice any errors resulting from running the install.

As suggested on the Kabanero slack channel, I'm attaching to logs from my Kabanero operator to allow the team to investigate. Unfortunately the file contains 10 days worth of logs and not just the install logs so its rather large.

[kabanero-operator.log](https://github.com/kabanero-io/kabanero-operator/files/3754179/kabanero-operator.log)

Here are the pipelines that were created:

<img width="1112" alt="Pipelines" src="https://user-images.githubusercontent.com/17197860/67265331-c8fc2c80-f4ad-11e9-939c-612d948968ff.png">

And here are the tasks that were created:

<img width="1102" alt="Tasks" src="https://user-images.githubusercontent.com/17197860/67265356-d2859480-f4ad-11e9-87cd-c02b04373927.png">

**Comment by ghodgkinson** [comment]
Related Slack discussion here: https://app.slack.com/client/T2HPVFQDA/CJZCYTD0Q/thread/CJZCYTD0Q-1570617067.001900

**Comment by kaczyns** [comment]
Hi @ghodgkinson - I see the following in your operator pod log:
```
"error":"no matches for kind \"Task\" in version \"tekton.dev/v1alpha1\""
```
This is an issue that we've been tracking/researching.  It appears that the controller-runtime client (what operator-sdk uses) reads from a cache, not directly from the API server.  The client is convinced that the `Task.tekton.dev` CRD is not registered yet, but it is probably there (just not present in the cache).  The collection_controller should be retrying, but I do not see that happening.  It looks like it's checking the digest for the pipeline/task, and sees that it has not changed since the last time it checked, and so does not try to apply it again.  But the previous apply had failed, so it should not care what the digest is, it should be applying again.

**Comment by kaczyns** [comment]
I did some more digging on this... the `no matches for kind` error message is printed by `k8s.io/apimachinery/pkg/api/meta/errors.go` and is a result of a call to the Kubernetes API server (REST).  So this is not a caching issue in the controller-runtime client.

We will focus on why the collection apply is not retried.

**Comment by kaczyns** [comment]
I have re-created this in the lab.  Whether or not the overall collection is marked failed depends on the last resource applied.  So for example if there was a pipeline and a task in the collection, and they were applied pipeline first and task second, if the task applied correctly then the overall collection is "applied correctly" even if the pipeline failed.  This can be recreated on 0.1.2 and 0.2.0.

@ghodgkinson where would you like to see this fixed?  You were on 0.1.2... is it OK to fix it in the 0.2.x stream, or the next release (0.3.x)?

**Comment by ghodgkinson** [comment]
Awesome - glad you've managed to track down the issue!

In terms of when I'd like to see the fix available, I'd say whichever gets this out soonest. I know there are a number of folks getting hands-on with Kabanero and this issue does cripple the "out of the box" experience for Appsody + Tekton.

Thanks for your efforts on this!

**Comment by kaczyns** [comment]
OK - the fix is currently available in the 0.3.0-rc.2 release.  Please re-open the issue if you'd like to see it delivered another way!

**Comment by ghodgkinson** [comment]
> OK - the fix is currently available in the 0.3.0-rc.2 release. Please re-open the issue if you'd like to see it delivered another way!

OK, I now see the significance behind the versions. We are using OKD 3.11 so please could you deliver the fix in the 0.2.x stream?

**Comment by ghodgkinson** [comment]
Thanks @kaczyns!

**Comment by kaczyns** [comment]
Release 0.2.2 is available now.  There are instructions on the release page to upgrade from 0.2.0 or 0.2.1.  Please let us know if you have any problems with it!

**Comment by nastacio** [comment]
It worked!

I added `KABANERO_BRANCH=0.2.2` to my usual install command:

KABANERO_BRANCH=0.2.2 openshift_master_default_subdomain=<mydomain> ./install-kabanero-foundation.sh

The shell script was cloned with:

```
kabanero_version=0.2.1
curl -sL https://github.com/kabanero-io/kabanero-foundation/archive/${kabanero_version}.zip -o kabanero-foundation.zip
```

Now I see all the pipelines.

**Comment by nastacio** [comment]
I take it back, I may have made a mistake and cloned the wrong version.
I do not see the pipelines, though I see this instruction at the end:

```
The installation script is complete.  You can now create an instance
of the Kabanero CR.  If you have cloned and curated a collection set,
apply the Kabanero CR that you created.  Or, to create the default 
instance:
oc apply -n kabanero -f https://raw.githubusercontent.com/kabanero-io/kabanero-operator/0.2.2/config/samples/default.yaml
```

I executed the step and it still did not create the pipelines.
@ghodgkinson confirms the same.

**Comment by ghodgkinson** [comment]
I've retried 3 times with 0.2.2 and get no pipelines or tasks. I did run the post-install script command. I'm attaching my pod log.

[kabanero-operator-55b9685684-22gxm.log](https://github.com/kabanero-io/kabanero-operator/files/3913015/kabanero-operator-55b9685684-22gxm.log)

**Comment by ghodgkinson** [comment]
Its worth noting that I could not get the uninstall script to work so I have been "manually" removing the namespaces before re-trying the install.

**Comment by nastacio** [comment]
I could not recreate the problem with the manual deployment of sample collections in my last 3 runs, so it is really up to the logs from @ghodgkinson

**Comment by ghodgkinson** [comment]
I followed the advice from Tim here...

> Greg is stuck in a loop - the kabanero instance named kabanero is being deleted.  the kabanero operator registers a finalizer, and is trying to process it.  however it is looking for the openshift route to the landing page that the operator created, but it is no longer there.  this is a bug but there are a couple of ways forward in the short term:
> 1. wait for a fix and release 0.2.3
> 2. oc edit the kabanero instance and delete the finalizer from the metadata.  this should allow the kabanero instance to go away, and then a subsequent oc apply of the kabanero instance from default.yaml should work normally.

**Comment by kaczyns** [comment]
Hi @ghodgkinson - we've not had any other requests for fixes in a 0.2.x release, so there hasn't been a release in some time.  Please let me know if you still require this fix in a 0.2.x release.  If you don't, I'd like to close this issue with the work-around provided.  Thanks!

**Comment by greghodgkinson** [comment]
We're in the process of moving from OpenShift 3.11 to 4.2 so I will no longer care about 3.11. So I'm fine with getting the fix in a newer release. Thanks!

**Comment by kaczyns** [comment]
yw - just holler if things change.  I'll close this issue.
