### ISSUE TITLE
Update kAppNav version in Kabanero 0.3.0

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/kabanero-operator#257]
@cvignola commented on [Wed Oct 23 2019](https://github.com/kabanero-io/roadmap/issues/102)

Update the kAppNav version in Kabanero 0.3.0 to kAppNav 0.1.2.

**Comment by kaczyns** [comment]
Note that this issue is in the operator repository, but it really belongs in the foundation repository since that's where the install shell script is.

**Comment by stephenkinder** [comment]
thanks @kaczyns   you're right of course but i find that repo is t monitored as well since there isnt a ton of code in it.

**Comment by cvignola** [comment]
@kaczyns @stephenkinder FYI, in case you guys have questions about what version of kAppNav goes where:  https://github.ibm.com/WASCloudTribe/design/blob/master/prism/releases.md

**Comment by marikaj123** [comment]
The high-level work for Collections to become visible in kAppNav:
1) appsody labels project resources
2) kAppNav display those labels
3) Kabanero operator only work is to include the new version of Appsody and kAppNav

**Comment by mezarin** [comment]
I deployed the yaml files that i received from @rlcundiff. I updated them to use the new *0.1.2-rc1 images, but there are a few issues with the current version. I made Roger aware of this.
