### ISSUE TITLE
Update kabanero-operators.yaml and prepare_release.sh for OLM

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#262]
In the `contrib` directory we have shell scripts which download YAMLs from some of Kabanero's pre-req operators, and then combine them into `kabanero-operators.yaml`.  Similarly, the `.travis/prepare_release.sh` script called by Travis uses `kabanero-operators.yaml` to attach `kabanero-operators.yaml` to a Github release.  This yaml was then used by the OKD 3.11 / Kabanero install script in kabanero-foundation.  Most of this is useless now that we are moving to OCP 4.2 and OLM.

For OCP 4.2, we should be generating a YAML file that contains:
- catalogsource for kabanero repository, using the correct TAG (or latest)
- all of the subscriptions that we need
- operatorgroup for kabanero namespace
- service mesh control plane and member role instances
- knative serving instance

This YAML can't be applied all at once, so I'd like to see it grouped into phases or categories using label selectors.  This is something that we tried to start doing with the "optional.yaml" file which currently only includes kAppNav.  We should get a group of operators that can be installed during phase 1, then a group for phase 2, etc until we have everything installed.
```yaml
metadata:
  labels:
    kabanero.io/install: subscriptions-phase0
```
and
```yaml
metadata:
  labels:
    kabanero.io/install: service-mesh
```
etc....
which can then be applied by the install script using:
```
oc apply -f filename --selector=kabanero.io/install/subscriptions-phase0
```

I suppose an alternative to having a single file with phases would be to have different files.  We would need to come up with a naming convention that makes sense.

We should have a goal of not having any yaml in the kabanero-foundation github repository, leaving only what can't be moved back to the operator cleanly.

**Comment by dacleyra** [comment]
Resolved by
https://github.com/kabanero-io/kabanero-operator/pull/273
