### ISSUE TITLE
Single install script for OCP 4.2

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#263]
The pieces of `kabanero-foundation/scripts/ocp42/install + createCRs` need to be combined into a single script that can be run to install:
1) The operators (kabanero and friends)
2) necessary objects (service mesh, serverless instances)
3) Optional components (kAppNav)

The script should not create the Kabanero CR instance, as other groups would like to be able to influence what CR instance is used.  Instead we should continue to print the location of `default.yaml` inside a pretty `*` box.

**Comment by dacleyra** [comment]
Resolved by
https://github.com/kabanero-io/kabanero-operator/pull/273
