### ISSUE TITLE
Update uninstall script for OCP 4.2

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#264]
There is a good start to our uninstall script for OCP 4.2 in the kabanero-foundation repository.

The uninstall script needs to change to do some of the same things that the current OKD 3.11 uninstall script does.  For example, we need to make sure that all CR instances are deleted before the relevant operator is deleted, so that finalizers have a chance to run.  There will need to be loops as we wait for the necessary CR instances to be deleted, and then remove the associated subscription.

**Comment by dacleyra** [comment]
Resolved by
https://github.com/kabanero-io/kabanero-operator/pull/273
