### ISSUE TITLE
Ingress to landing page and CLI pod is broken on OCP 4.2

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-operator#265]
Ingress to landing page and CLI pod is broken on OCP 4.2

**Comment by davco01a** [comment]
had to edit: `oc edit smmr default -n istio-system`

and remove kabanero from:

```
spec:
  members:
  - knative-serving
  - openshift-pipelines
 - kabanero
```

**Comment by kaczyns** [comment]
When we deploy the landing page and CLI service, we need to annotate the pods so that istio leaves them alone.  I forget the name of the annotation.

**Comment by kaczyns** [comment]
@davco01a Dave, I am unable to re-create this on my cluster.  Would you mind adding `kabanero` back to the service mesh member role, and re-cycle your CLI and landing page pods, so that I can collect logs and test whether the fix works?

**Comment by kaczyns** [comment]
There have been more occurrences of this.  The service mesh treats the network differently than the version of istio and knative that we had been using in Kabanero 0.2.  We can apply a different network policy to make the configuration closer to what it had been.
