### ISSUE TITLE
Delays seeing updates to Kabanero collections

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-operator#274]
After a change is made to update a Kabanero Collections object there is sometimes as much as a 2-3 minute delay to see the change reflected in the collection object in Kube

above can be tested using the Kabanero CLI deactivate or REFRESH (soon to be renamed to SYNC) function

To Reproduce

kabanero deactivate nodejs

Change the desiredState of a Kab collection object to active or inactive and see how long it takes to show up

Expected behavior
.
Expect to see these changes almost immediately, sometimes takes ~3mins

Actual behaviour
What is the actual behaviour.
Sometimes delays of almost 2-3 minutes to see the changes in Kabanero

Environment Details (please complete the following information):

If applicable please specify:

CLI version: 0.3.0-alpha.1
Collection you are using: my owned cloned version of https://github.com/kabanero-io/collections using the prescribed process at https://kabanero.io/docs/ref/general/collection-building.html
Screenshots

Additional context

**Comment by davco01a** [comment]
oc edit smmr default -n istio-system

and deleting openshift-pipelines fixed it

**Comment by davco01a** [comment]
Feel free to close this if it's already handled by another issue

**Comment by kaczyns** [comment]
The problem with the service mesh member role is fixed by #272 .
