### ISSUE TITLE
Kabanero operator should prevent a 2nd instance in the namespace

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#28]
It is not valid to have two kabanero instances in the same namespace, since some of the dependencies cannot be installed twice in the same namespace.  The kabanero operator should prevent a second instance from being processed, if a first instance already exists in the namespace.

**Comment by kyleschlosser** [comment]
See #57

**Comment by kaczyns** [comment]
Fixed in #330
