### ISSUE TITLE
Uninstall of Kabanero 0.3.rc2 not finishing.

### ISSUE THREAD

**Issue by csskinner25** [kabanero-io/kabanero-operator#294]
I installed the Kabanero 0.3.rc2 release. I then tried to uninstall. The uninstall hangs at 

****
 grep '.*\.maistra\.io'
+ xargs -r -n 1 oc delete
+ oc get crds -o name
customresourcedefinition.apiextensions.k8s.io "servicemeshmemberrolls.maistra.io" deleted
****

Working with Dan , one problem that was seen is that the csv's are not getting cleaned up by uninstall. 

********
 oc --all-namespaces=true get csv
NAMESPACE                              NAME                                        DISPLAY                          VERSION              REPLACES                              PHASE
kabanero                               appsody-operator.v0.2.2                     Appsody Operator                 0.2.2                appsody-operator.v0.2.1               Succeeded
kabanero                               elasticsearch-operator.4.2.1-201910221723   Elasticsearch Operator           4.2.1-201910221723                                         Succeeded
kabanero                               knative-eventing-operator.v0.9.0            Knative Eventing Operator        0.9.0                knative-eventing-operator.v0.8.0      Succeeded
kabanero                               openshift-pipelines-operator.v0.7.0         OpenShift Pipelines Operator     0.7.0                openshift-pipelines-operator.v0.5.2   Succeeded
kabanero                               serverless-operator.v1.1.0                  OpenShift Serverless Operator    1.1.0                serverless-operator.v1.0.0            Succeeded
kabanero                               servicemeshoperator.v1.0.2                  Red Hat OpenShift Service Mesh   1.0.2                servicemeshoperator.v1.0.1            Succeeded
openshift-monitoring                   appsody-operator.v0.2.2                     Appsody Operator                 0.2.2                appsody-operator.v0.2.1               Succeeded
openshift-monitoring                   elasticsearch-operator.4.2.1-201910221723   Elasticsearch Operator           4.2.1-201910221723                                         Succeeded
openshift-monitoring                   jaeger-operator.v1.13.1                     Jaeger Operator                  1.13.1                                                     Succeeded
openshift-monitoring                   knative-eventing-operator.v0.9.0            Knative Eventing Operator        0.9.0                knative-eventing-operator.v0.8.0      Succeeded
openshift-monitoring                   serverless-operator.v1.1.0                  OpenShift Serverless Operator    1.1.0                serverless-operator.v1.0.0            Succeeded
openshift-monitoring                   servicemeshoperator.v1.0.2                  Red Hat OpenShift Service Mesh   1.0.2                servicemeshoperator.v1.0.1            Succeeded
openshift-operator-lifecycle-manager   appsody-operator.v0.2.2                     Appsody Operator                 0.2.2                appsody-operator.v0.2.1               Succeeded
openshift-operator-lifecycle-manager   elasticsearch-operator.4.2.1-201910221723   Elasticsearch Operator           4.2.1-201910221723                                         Succeeded
openshift-operator-lifecycle-manager   jaeger-operator.v1.13.1                     Jaeger Operator                  1.13.1                                                     Succeeded
openshift-operator-lifecycle-manager   knative-eventing-operator.v0.9.0            Knative Eventing Operator        0.9.0                knative-eventing-operator.v0.8.0      Succeeded
openshift-operator-lifecycle-manager   openshift-pipelines-operator.v0.7.0         OpenShift Pipelines Operator     0.7.0                openshift-pipelines-operator.v0.5.2   Succeeded
openshift-operator-lifecycle-manager   packageserver                               Package Server                   0.11.0                                                     Succeeded
openshift-operator-lifecycle-manager   serverless-operator.v1.1.0                  OpenShift Serverless Operator    1.1.0                serverless-operator.v1.0.0            Succeeded
openshift-operator-lifecycle-manager   servicemeshoperator.v1.0.2                  Red Hat OpenShift Service Mesh   1.0.2                servicemeshoperator.v1.0.1            Succeeded

*****

Ran oc --all-namespaces=true delete csv --all to try to clean that up and then ran uninstall again 
but it hung in the same place. 

Dan saw this while helping me 

************
The uninstall order is: remove the instance, remove the subscription,csv, then make sure the crds are deleted
but somehow the instance is still there
but it wont clean up because the controller is already removed

************
Tried this 

***************
 oc get --all-namespaces=true servicemeshcontrolplanes.maistra.io
NAMESPACE      NAME            READY
istio-system   basic-install   True
[root@css-inf ~]# oc -n istio-system delete servicemeshcontrolplanes.maistra.io basic-install
servicemeshcontrolplane.maistra.io "basic-install" deleted

*************
This also hung. I am unable to get uninstall to finish. 

I tried to reinstall to put the controllers back  and it got stuck 
*********

 oc get clusterserviceversion servicemeshoperator.v1.0.2 -n openshift-operators '--output=jsonpath={.status.phase}'

******************

I never saw the pod try to start .

I am not the only one seeing install and uninstall problems.  

Let me know what logs or info you need.

**Comment by gecock** [comment]
@marikaj123 we think this is a stop-ship candidate for 0.3.0

**Comment by marikaj123** [comment]
Platform Issue to pull images from registery.

**Comment by dacleyra** [comment]
Added additional CSV cleanup. Change is in master, after 3.0-rc3

**Comment by marikaj123** [comment]
The fix is in Master.
