### ISSUE TITLE
Update Eclipse Che tag to 7.3.1

### ISSUE THREAD

**Issue by johnmcollier** [kabanero-io/kabanero-operator#296]
The versions.yaml for the operator currently has the Che version set to 7.3.0: https://github.com/kabanero-io/kabanero-operator/blob/master/config/versions.yaml#L42

We just delivered a fix in Codewind that required us to move up to Che 7.3.1, would the version be able to be updated in that file too? Thanks!

**Comment by makandre** [comment]
Please also update kabanero-che to `0.6.0` which corresponds to Che 7.3.1

**Comment by kaczyns** [comment]
Fixed by #297.  Thanks guys!
