### ISSUE TITLE
Upgrade strategy for 0.3.0 -> 0.4.0 and beyond

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#314]
It may be too early to have a dedicated upgrade script, but we need to start thinking about how we want users to upgrade from 0.3.0 to 0.4.0, and again for future releases of Kabanero.  Some things to think about:
1) Any subscriptions that we are pinning to a particular level thru the use of channels (ie kabanero operator, openshift pipelines) will probably need to be updated to use a different channel.  An updated `kabanero-operator-registry` will need to be applied, and then the subscription modified.
2) Some components that are not installed via operators may change.  For example, we may need to use a new version of the Tekton dashboard.

Some strategies that we could use to perform the upgrade:
1) Have a dedicated upgrade script.  This could be tied to a particular release (ie 0.3.0 -> 0.4.0, then a different one for 0.4.0 -> 0.5.0, etc).  We'd release one each release that takes you from the previous release to the current release.
2) Have the install script written in such a way that it can handle an upgrade.  This might work if OLM can tolerate changes to the catalog (being replaced) and the subscription instances (channel changing).  There would be some questions around the yamls we apply... using the Tekton dashboard as an example, how do we handle the case where an object is no longer used by the newer version?  We need a way to clean it up.
3) Some other way....

Lets spend some time experimenting with OLM to see how it behaves when components are upgraded (catalog and/or subscriptions) and try to come up with a more concrete strategy that we think will work for upgrade.

**Comment by dacleyra** [comment]
0.3.x -> 0.4.0

1. Notify about necessary object removals
1. Apply the new Kabanero CatalogSource with 0.4.0 CSV
1. Wait for Kabanero CatalogSource to be Ready
1. If necessary, notify & remove any CRs with modified/incompatible-alpha APIs of prereq CSVs 
1. Remove old subscriptions, if sub has changed
1. Add any new subscriptions
1. Interact with the Subscription / OLM to install any new CSVs from relevant CatalogSources
1. Update KappNav if it is present.
1. Print message to apply the new Kabanero CR instance to get new Collection versions

**Comment by kaczyns** [comment]
Dan and I had a brief chat this morning regarding the update script.  There is still not a clear preference for whether we have an install script that also can handle an upgrade, or a dedicated upgrade script.  however in either case, it will be important that the script enforces that the upgrade must be stepwise.  that is, it might support 0.3.x -> 0.4.0 or 0.4.0 -> 0.4.1, but would not support 0.3.x -> 0.5.0.  This is important to avoid bloating the script with logic to handle any version of Kabanero.  The script should be able to handle moving from one release to the next, and then the subsequent version's install script will have deleted that logic from the previous release and focus on handling the upgrade of the current release.

**Comment by dacleyra** [comment]
Will need to update checksub

https://github.com/kabanero-io/kabanero-operator/blob/master/deploy/install.sh#L44

For an upgrade, can end up getting the old installplan before the new one is emitted

**Comment by kaczyns** [comment]
I think we have our strategy in place now.  I am closing this issue.
