### ISSUE TITLE
Update Kabanero 0.4.0 install to pick up kAppNav 0.1.4 

### ISSUE THREAD

**Issue by cvignola** [kabanero-io/kabanero-operator#335]
Need to update the image tags in the install script.

Affected file is https://github.com/kabanero-io/kabanero-operator/blob/release-0.4/deploy/optional.yaml

Tag value 0.1.2 must be changed to 0.1.4.

**Comment by kaczyns** [comment]
Kabanero 0.4.0-rc.1 includes kAppNav 0.1.4
