### ISSUE TITLE
Correct the behavior of desiredState in the Stack CR

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#353]
The operator's implementation of `desiredState` in the Stack CR instance drifted from its intended behavior.  The `desiredState` was meant to be an over-ride used by the Kabanero CLI.  The current implementation uses it as a general purpose activate/deactivate switch.  The following changes should be considered:
1) The `desiredState` field of the Stack CR should be an over-ride and should be the empty string by default.
2) The stack controller should treat an empty `desiredState` as `activate`, and should activate the stack.
3) The Kabanero controller should always set the `desiredState` to the empty string when it creates a stack, or when it adds a version of a stack to the versions array of the Stack CR instance.
4) The Kabanero controller should ensure that the set of Stack CR instances matches exactly the view of the Stack Hubs configured in the Kabanero CR instance, unless a Stack CR instance has the `desiredState` field set to a non-empty string.  In this case, the Kabanero controller should not alter that stack version or Stack CR.  Note that within a Stack CR, some versions may have the `desiredState` field set, and some may not.

This will result in a behavior change, and I would suggest having a `v1alpha2` version of the Kabanero CRD which eliminates the `activateDefaultCollections` field.

**Comment by kaczyns** [comment]
I am working on this over here: https://github.com/kaczyns/kabanero-operator/tree/v1alpha2-sdk11
This is going to need to be staged - I wanted to remove the requirement that the Collection CR instance has a Kabanero owner at the same time, but I don't think that will be possible.  I'd like to wait until the current backlog of PRs is reviewed / merged before making more progress here.

**Comment by marikaj123** [comment]
The release was originally set to 0.6.0 and I have moved it to a later one.   Please feel free to to reset it, as needed.

**Comment by kaczyns** [comment]
We need to remove the note that was added in kabanero-io/docs#338 now that we've changed the behavior of desiredStatre.  The kabanero operator is now deleting stacks that are no longer present in the index (unless the desiredState is set to a non-null value).
