### ISSUE TITLE
Add GitHub OAuth variables to Kabanero CRD spec

### ISSUE THREAD

**Issue by alohr51** [kabanero-io/kabanero-operator#355]
The console (previously called "landing") application is going to start using GitHub OAuth services to get information from the logged in user. This is the start of our role based approach.

The console app will need some information about OAuth such as:

(required)
* OAuth client ID - obtained from creating an OAuth app in GitHub settings
* OAuth client secret - obtained from creating an OAuth app in GitHub settings
   * Maybe these should be in a kubernetes secret instead of the CRD

(Optional, github.com is default)
* authorizationEndpoint - for example: `https://github.com/login/oauth/authorize`
* tokenEndpoint - for example: `https://github.com/login/oauth/access_token`
* userApi - for example: `https://api.github.com/user/emails`
* website - for example: `https://github.com`

these are all configurable options from the [Liberty GitHub Social Login feature](https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.liberty.autogen.nd.doc/ae/rwlp_config_githubLogin.html). I believe the listed are the only ones really needed depending on where the GitHub server is

If using Public GitHub.com, then only `client ID` and `client secret` of these need to be specified, as social login uses github.com as the default configured

I was thinking a good spot for these might be in the Kabanero `spec.github`. One question though, is there a way to inject these values as env vars to the console pods? Our liberty app has a server xml feature configuration (social login) that would need to read these values on start up.

**Comment by alohr51** [comment]
Another possible option is to have a kubernetes secret with the `xml` we need for the server.xml. 

Then we can:
1. Create a secret with the xml we need
1. Volume mount the secret on the console pods
1. Liberty can optionally include that file to include the configuration needed
   * Currently this OAuth setup will be **optional** the console app will still work without it, but a part of the app will be enhanced to use this optional GitHub sign in.

example of secret contents
```
<githubLogin
clientId="xxxxx"
clientSecret="xxxxx" 
scope="read:org,read:user,user:email"
authorizationEndpoint="https://github.com/login/oauth/authorize"
...
 />
```

**Comment by kaczyns** [comment]
I think I would prefer to have the user put the information in the CR instance (either directly, or in a secret and then have the user name the secret in the CR instance), and then export those as environment variables to the console pod.  If the operator produces the xml, and then puts it into a secret, then changing the format of the xml requires a change to the operator and the console.  If the operator just sets environment variables, then the console can manipulate the values as necessary.

We should talk about where the information should be in the Kabanero CR instance. Andrew is setting up some time for us to discuss it.

**Comment by alohr51** [comment]
@kaczyns's diagrams for this work can be seen in this comment https://github.com/kabanero-io/kabanero-landing/issues/65#issuecomment-565087490

**Comment by kaczyns** [comment]
@alohr51 @stephenkinder and I met today to discuss this... we agreed to try this:
1) No update to the Kabanero CRD
2) Oauth clientId and clientSecret will be in a secret which must be named "kabanero-github-oauth-secret".  kab user must create the secret.
3) Kabanero Operator will attempt to mount that secret in the file system for the console container to read (update the deployment yaml) if the secret exists
4) Kabanero operator will manipulate the existing `spec.github.apiUrl` to generate the hostname and userApi used by the liberty social login feature.  These values will be exposed to the console container as environment variables (names to be determined).
5) Console container will add a shell script which looks to see if the secret is mounted, and add a Liberty config dropin with the social login configuration if the secret exists.
6) Console container will default use default `github.com` if the environment variables for hostname and userApi are not set.

Please feel free to propose changes to the above, I'm not sure we covered it all in our meeting and I might have made some assumptions which are not appropriate.

**Comment by kaczyns** [comment]
I am going to try and make this more concrete.  Thanks to @chunlongliang-ibm for clarifying several points on the GHE URLs:
1) Oauth clientId and clientSecret as defined in the previous comment.
2) if `spec.github.apiUrl` is empty, assume it's set to `api.github.com` and proceed to the next step.
3) Parse `spec.github.apiUrl` using the golang url parser.  If the hostname portion is `api.github.com`, then set the following environment variables: `USER_API` = `https://api.github.com/user`, `AUTHORIZATION_ENDPOINT` = `https://github.com/login/oauth/authorize`, `TOKEN_ENDPOINT` = `https://github.com/login/oauth/access_token`, `WEBSITE` = `https://github.com`.  Skip step 4.
4) Assuming we got a valid hostname back from the parser in step 3, set the following environment variables:  `USER_API` = `https://[hostname]/api/v3/user`, `AUTHORIZATION_ENDPOINT` = `https://[hostname]/login/oauth/authorize`, `TOKEN_ENDPOINT` = `https://[hostname]/login/oauth/access_token`, `WEBSITE` = `https://[hostname]`.  Replace `[hostname]` with the hostname read in step 3.
