### ISSUE TITLE
Kabanero & Collection integration tests

### ISSUE THREAD

**Issue by dacleyra** [kabanero-io/kabanero-operator#356]
@mtamboli 

Some additional tests around lifecycle, tests 20-23
https://github.com/dacleyra/kabanero-operator/tree/addtests/tests

Do we want more of these kinds of tests?

**Comment by mtamboli** [comment]
@dacleyra I think these are good tests to add for each kabanero operator PR. We can add to the list as we come across various issues which can be added to the tests to catch problems early.

**Comment by dacleyra** [comment]
merged, closing
