### ISSUE TITLE
Investigate RBAC for Kabanero CR targetNamespaces

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#361]
In Kabanero 0.3.0, the Kabanero install script changed from installing the Appsody at the namespace scope, to the cluster scope.  OLM did not provide a convenient way to give a list of namespaces which the Appsody Operator should watch (which we would derive from the `targetNamespaces` field of the Kabanero CR instance).  As a result, any the Appsody operator is watching all namespaces, so any service account which has permission to deploy applications to that namespace will be able to do so, regardless of how the target namespaces are configured in the Kabanero CR instance.

An Appsody application creates an `AppsodyApplication` CR instance at the end of its `app-deploy.yaml`.  Typically this runs at the end of a deploy pipeline.  The service account that runs this pipeline would be the one that needs permission to create an `AppsodyApplication` CR instance in the target namespace.  An example service account and roles are currently generated in the Kabanero install script (see deploy/kabanero-customeresources.yaml, label `24-pipeline-sa`).  This creates a `ClusterRole` and a `ClusterRoleBinding` which include permissions to deploy an `AppsodyApplication` CR instance to any namespace.

We should investigate generating a `Role` that is permitted to create / update an `AppsodyApplication` for the namespaces listed in `targetNamespaces` (or the Kabanero control namespace if no namespaces are listed) of the Kabanero CR instance.  Someone could then create, if they choose to, a `RoleBinding` which binds that role to the service account that runs their pipelines.

Even better, we could generate the `ServiceAccount` and `RoleBinding`(s) in the kabanero controller, such that the resulting service account could be used as-is if the customer chooses to.  And if not, they could still use the `Role` we generate and create their own `RoleBinding` to their own `ServiceAccount`.

Some investigation probably needs to happen around how to create a `RoleBinding` for a namespace other than the one where the `ServiceAccount` exists.  I suspect that it's possible but I have not done it personally.

**Comment by dacleyra** [comment]
As-Is, we have in kabanero-customresources.yaml
  - ClusterRole kabanero-pipeline-role (ClusterRole just makes the Role available for use by any namespace)
  - ServiceAccount kabanero-pipeline 
  - ClusterRoleBinding kabanero-pipeline-cluster-role-binding

To-Be, at a minimum
  - remove ClusterRoleBinding
  - Implement in the controller
    - For each Kabanero, create individual namespace'd RoleBinding for each targetNamespace

At this point, whoever can manipulate a Kabanero instance, can grant priveledge to that SA in an aribtrariy namespace
Kabanero instance is only watched in the operator (kabanero) namespace, so I believe this is ok, with the assumption only the admin has (write) access. No one creating a rogue Kabanero instance that grants privs.

Optional
  - ServiceAccount kabanero-pipeline could be generated/owned by the operator
  - ClusterRole kabanero-pipeline-role could be generated/owned by the operator


This is an example
https://medium.com/faun/kubernetes-rbac-use-one-role-in-multiple-namespaces-d1d08bb08286

**Comment by kaczyns** [comment]
I think that this is a good plan.  I am hesitant to have the operator generate/own the service account, and the overall ClusterRole, because the user may have implemented their own pipelines which require different permissions than the ones we have defined in the sample one (from `install.sh`).  I wonder if it would be better to have the user give us the name of the service account in the Kabanero CR instance spec section, or perhaps a list of Roles and/or ClusterRoles that they want associated with the service account, and we somehow merge them together?  The simplest thing would be for them to give us the SA name, then we could just create a RoleBinding for Appsody and let the user take care of the rest.

**Comment by kaczyns** [comment]
I'd like to try to tackle this for 0.8.0.  Here's what we should be doing:
1) Remove the `AppsodyApplication` completely from the `kabanero-pipeline-role` in `deploy/kabanero-customresources.yaml`.  This is the sample pipeline role.  It will not have any permission to deploy an appsody application.
2) Create a second `ClusterRole` in the `deploy/kabanero-customresources.yaml` which contains only `AppsodyApplication` permissions.  Can just cut them out or `kabanero-pipeline-role` and paste them into the new `ClusterRole`.  I would propose `kabanero-pipeline-deploy-role` for the new role but you can pick whatever you want.  Note that there will be no role binding for this role in `deploy/kabanero-customresources.yaml`.
3) The kabanero controller should parse the Kabanero CR instance looking for target namespaces.  For each one it finds, it should create a `RoleBinding` linking the `kabanero-pipeline` service account in the `kabanero` namespace, with the `kabanero-pipeline-deploy-role` in the target namespace.  If there are no target namespaces listed, then use the `kabanero` namespace instead.  There may end up being several `RoleBinding` objects created among the namespaces.  Remember that controller-runtime does (or did) have trouble getting objects from other namespaces, unless you use `unstructured`.  That may have been fixed, I'm not sure, I don't think we've tried since coming up from controler-runtime 0.1.x.
4) We'll need to add some logic to the kabanero controller to deal with when the list of target namespaces changes.  we'll need to delete the `RoleBinding` for the namespaces that are no longer in the target namespace list.  We could accomplish this by just doing a search across all of the namespaces, and deleting the ones that we don't want.  Or we could maintain something off on the side (maybe an annotation the Kabanero CR) that keeps track of which namespaces currently have the `RoleBinding`), and we can keep that up to date.  I'm open to other suggestions.

Doing these four things will (I think) make it so the `kabanero-pipeline` service account only has permission to deploy applications to the target namespaces.  In a separate issue we'll have to deal with doing the same for other service accounts (if the user chooses to use their own service account).  We can document that we're creating the `Role` for deploy, and that the user can create a `RoleBinding` if they choose to.  Later, we can choose to let the user input what service account they want to use, and we can create the role binding for them.

**Comment by kaczyns** [comment]
This was fixed in #585
