### ISSUE TITLE
Setting Accept-Encoding header to gzip has unintended consequences

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#367]
A while back when using a non-github web server to serve a collection hub I had created, I found that the web server was helpfully un-gzipping the pipeline zips for me.  This was great but the code was expecting them to be gzipped and so the collection controller could not use them.  I added the "Accept-Encoding" header and set it to "gzip" to get around this.  All seemed to be well.

Recently someone was trying to use GHE to host their collection.  The GHE uses some sort of OAuth and when we tried to retrieve the kabanero-index.yaml, we received a login web page instead.  However the web page was gzipped, so we couldn't tell what it was.  When we removed the "Accept-Encoding" header, GHE returned the page in text mode and we could see what the problem was.

We need to consider how we're setting "Accept-Encoding".  Ideally I think we'd just set that if the file extension was ".gz".  We'll need to parse the URL and see what the extension is before setting that header.  There may be other solutions too.  We could just not set the header at all, and I think the main-line supported paths would be covered, but we'd lose some flexibility when unit testing the collection controller.

**Comment by covener** [comment]
What was your non-github webserver? It's bizarre that it would decompress *.gz on the fly for a client just because it didn't have Accept-Encoding: gzip.  There is not really negotiation happening when you request *.gz explicitly.

I wonder if there wasn't some proxy between your client and the webserver that wanted to see the contents?

**Comment by kaczyns** [comment]
The preferred way appears to be to set `DisableCompression` on the HTTP transport.  See:
https://golang.org/pkg/net/http/

What was probably happening in the error case, was the golang HTTP client was setting the `Accept-Encoding: gzip` header on our behalf, and then when it got gzipped output back, was uncompressing it.  The client was not expecting this.  Setting `DisableCompression` will prevent the golang HTTP client from adding the accept encoding header.
