### ISSUE TITLE
Add a stack controller to eventually replace the collection controller

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#388]
The stack controller is essentially a copy of the collection controller, with some twists:
* Obviously the name `collection` should be replaced with `stack` everywhere.  For example the container image will be named `kabanero-operator-stack-controller`
* The stack controller will watch kabanero.io/v1alpha2 Stack CR instances
* The finalizer should be renamed to have stack in the name instead of collection
* The stack controller should not reference the parent kabanero instance at all.  It should not be obtaining the repository URL from the kabanero instance to retrieve any information.  It should not be setting the owner of stack instances to be the kabanero instance.
* The stack CR instance will have the pipeline URL set in it.  It will also have the image list set in it.  This information should not be obtained from the index yaml.
* Note that the v1alpha2 stack CR instance does not have fields for the singleton version, nor any upgrade information, so this information should not be calculated by the controller.  It should only process the versions present in the `spec.versions` array.

For the time being, the Kabanero controller should be deploying a stack controller in addition to the collection controller.  This means the stack controller will need its own orchestration, etc.  Hopefully this can mostly be copied from the collection controller orchestration.

**Comment by kaczyns** [comment]
If the stack controller reads a Stack CR instance that does not have pipelines or images set, it should set an `errorMessage` in the status, and refuse to activate that version of the stack.  The admission controller webhook will be modified to handle this case as well, but it's always possible that objects can get thru anyway.

**Comment by kaczyns** [comment]
There has been some churn lately regarding the `repositoryUrl` in the Stack CR instance (the repository URL points to the stack index).  The original v1alpha2 CRD for Stack had the `repositoryUrl` specified, but there is no reason to include it.  The Stack controller will not be reading any information out of the stack index.  Therefore we will be removing the `repositoryUrl` from the v1alpha2 Stack CRD.

**Comment by dacleyra** [comment]
merged, closing
