### ISSUE TITLE
Webhook validation for v1alpha2 Stack CRD

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#391]
When a Stack CR instance is created, it should be validated:
* It must have a `name` set in the `spec`
* It must have at least one version in the versions array
* For each version in the versions array, it should contain ~~a URL,~~ a pipeline URL ~~and a triggers URL~~
* Each pipeline URL should contain a Sha256
* If the `desiredState` is set, it must be set to one of `active` or `inactive`
* At least one `Image` should be set for each version in the versions array

For each of these conditions, if the admission controller webhook rejects the object, it should return a message indicating what is not correct, and how to fix it (if it's not obvious).  For example, saying "The Stack instance must contain a pipeline URL for version 0.2.5" is sufficient because any URL can be given.  For `desiredState` it may be necessary to list the valid values.

**Comment by kaczyns** [comment]
I think that the Kabanero webhook validation needs to be modified to include v1alpha2 of the CRD.  We should continue to verify that only one instance of Kabanero per namespace exists (at either version).

**Comment by dacleyra** [comment]
merged, closing
