### ISSUE TITLE
Kabanero v1alpha1 -> v1alpha2 migration strategy

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#396]
I had initially been concerned about how to migrate users from their existing v1alpha1 Kabanero CR instances, which specifies `spec.collections`, to the v1alpha2 Kabanero CR instance, which specifies `spec.stacks`.  However, I've learned that `etcd` will serialize whatever you give it, and isn't going to remove or update fields unless you tell it to.  So when we switch the storage version of the Kabanero CRD from v1alpha1 to v1alpha2, all of the existing fields will remain, and can be retrieved, provided the object that you're retrieving into contains those fields.

It also appears to be impossible to determine what version a specific CR instance is stored at, because with conversion strategy `None` (the only one supported in OCP 4.2), the API server will just set the API version in the object to what you ask it for, and if you don't ask for anything, it will set it to the latest most-supported version that is served (ie if it was written at v1alpha1, but v1alpha2 is served, and you didn't ask for a version, you get v1alpha2).  If you ask for a version, it will give you that version, regardless of what version is actually stored.

OK so anyway, here's my proposal:  The Kabanero controller will first get the requested Kabanero CR instance as unstructured.  It will look to see if the instance has a `spec.collections` section.  If it does, it will rename `spec.collections` to `spec.stacks`, update the api version from v1alpha1 to v1alpha2 (just to be consistent) and then re-write the object, then return.  The reconciler will be driven again immediately (because the object changed) but this time it will not contain `spec.collections` and so can be read in as `v1alpha2` and we'll process it as per usual.

We'll need to decide what to do about `spec.version`.  Ideally, if someone specified `spec.version` to be less than 0.6.0, we'd have the kabanero controller continue to create `Collection` objects, since those versions don't contain a stack controller.  And then for 0.6.0 and greater, create `Stack` objects.  I don't know how practical that is.  We may end up just removing all lower versions from the version data such that the 0.6.0 operator can only configure a 0.6.0 kabanero.

**Comment by dacleyra** [comment]
As a followup to #388 
  - the pkg/controller/kabaneroplatform/stack-operator needs to be created
  - kabaneroplatform_controller need to handle the v1alpha2 version
  - update full.yaml

**Comment by kaczyns** [comment]
WRT my first comment... `etcd` serializes whatever you give it because we have not enabled pruning on our CRDs.  We are using v1beta1 of the CRD api, where pruning is opt-in and optional.  Soon we'll be forced to v1 where pruning is enabled and not optional.  It's not clear when we'll get there (OCP 4.3 still uses Kube 1.16 where it's optional).

**Comment by kaczyns** [comment]
This was fixed with #425
