### ISSUE TITLE
Investigate moving up ServiceMesh and Serverless operators for 0.6.0

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#420]
We should try to get closer to what is supported by OpenShift for the 0.6.0 release.

**Comment by kaczyns** [comment]
It looks like in OCP 4.3, service mesh is at v1.0.4 in the `1.0` channel, and serverless is at v1.3.0 in the `techpreview` channel.

**Comment by dacleyra** [comment]
merged, closing
