### ISSUE TITLE
kabanero operator 0.5.0  not updating collections dynamically

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-operator#433]
When collections URL is updated, kabanero operator is not making those updates unless kabanero pods or collection instances are deleted.

This is regression problem.

**Comment by marikaj123** [comment]
The fix will go into Stacks for 0.6.0 release.

**Comment by marikaj123** [comment]
FIx is going in 0.6.0.

**Comment by marikaj123** [comment]
@mtamboli - Good news from @mezarin - The fix was merged in an alpha 2 release. Ready for testing.

**Comment by mtamboli** [comment]
Thanks @marikaj123 will pick up this fix with 0.6.0 rc builds.

**Comment by mtamboli** [comment]
I tested this with 0.6.0.rc.1 build. Updated to operator are being picked up dynamically.
