### ISSUE TITLE
Update status correctly when there is a configuration problem

### ISSUE THREAD

**Issue by dacleyra** [kabanero-io/kabanero-operator#447]
we have this problem where if you have a configuration problem, we don't update the status of the CR instance, so you never find out about it.  it's only after the reconciler gets completely thru all of the components, that it moves on to updating status. An example case is not setting the secret required by the sso component.

**Comment by marikaj123** [comment]
@dacleyra - Can you please select a release as to when we expect to have the fix. Thank you.
