### ISSUE TITLE
KabaneroStatusKabaneroInstance.SERIALIZED_NAME_READY shoud be True not ready

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-operator#463]
KabaneroStatusKabaneroInstance.SERIALIZED_NAME_READY shoud be True not ready or 
k.getStatus().getKabaneroInstance().getReady()  should return `ready`

k.getStatus().getKabaneroInstance().getReady() . returns the value `True` not `ready`

**Comment by davco01a** [comment]
```
Operator ready: True
Operator error msg: null
```

**Comment by kaczyns** [comment]
Dave and I spoke about this.  There was a mis-understanding about what would be in the `ready` field.
