### ISSUE TITLE
Move up to latest Tekton Dashboard 0.5.2

### ISSUE THREAD

**Issue by anneqm** [kabanero-io/kabanero-operator#478]
Tekton Dashboard with webhooks extension 0.5.2 will be available soon. This is the release that should be used in the final kabanero 0.6.0 to include proper display of versions in the openshift-pipelines  namespace. 

- this dot release will implement https://github.com/tektoncd/dashboard/issues/1034.

**Comment by anneqm** [comment]
The Dashboard 0.5.2 is available now at https://github.com/tektoncd/dashboard/releases/tag/v0.5.2

**Comment by kaczyns** [comment]
This is currently available in branches `release-0.6` and `master`.
