### ISSUE TITLE
0.6.0 pipelines are not being recreated when deleted

### ISSUE THREAD

**Issue by dacleyra** [kabanero-io/kabanero-operator#483]
Kabanero configured with full.yaml
Delete a pipeline
Expect the pipeline to be recreated

**Comment by kaczyns** [comment]
We'll need to check the watches that the stack controller is setting up.  I would not be surprised if it was not watching for pipelines and tasks.  And it can't watch for trigger templates or bindings in the tekton-pipelines namespace (at least it couldn't when we were using controller-runtime 0.1.x... maybe it can now)

**Comment by marikaj123** [comment]
@dacleyra - Can you please provide us with a status on this issue?

**Comment by dacleyra** [comment]
A PR is ready for review

**Comment by marikaj123** [comment]
@dacleyra -Is the defect ready to close?

**Comment by dacleyra** [comment]
PR was merged, closing
