### ISSUE TITLE
should Stack controller create Kabanero stacks with "image" string instead of "images" lists?

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-operator#493]
should Stack controller create Kabanero stacks with image strings instead of images lists?

new stack hub index.yaml for image:

image: docker.io/kabanerobeta/java-microprofile:0.2.25

used to be:

```
images:
  - id: java-microprofile
    image: docker.io/kabanerobeta/java-microprofile:0.2
```

**Comment by davco01a** [comment]
But stacks are still being cre\ated like this:

```
spec:
  name: nodejs
  versions:
  - desiredState: active
    images:
    - id: Node.js
      image: docker.io/kabanerobeta/nodejs

**Comment by davco01a** [comment]
and if this changes...the operator-java-bindings will need to change:

e.g.

specVersion.setImages(stackSpecVersion.getImages());

**Comment by kaczyns** [comment]
Hi Dave - for now, we are going to leave it the way it is.  I realize that the stack index only has `image` but this is completely unrelated to how the `Stack` object is constructed.  The original `Collection` specified images, of which you could have multiple, and so I'd like our `Stack` to not preclude someone from having multiple images in the future.
