### ISSUE TITLE
update default.yaml to use apiVersion: kabanero.io/v1alpha2

### ISSUE THREAD

**Issue by tam512** [kabanero-io/kabanero-operator#503]
Please update the https://raw.githubusercontent.com/kabanero-io/kabanero-operator/0.6.0-rc.2/config/samples/default.yaml to use `apiVersion: kabanero.io/v1alpha2`

**Comment by marikaj123** [comment]
FIxed in rc-3.  @tam512 - please verify. Thank you.

**Comment by tam512** [comment]
Verified in https://raw.githubusercontent.com/kabanero-io/kabanero-operator/0.6.0-rc.4/config/samples/default.yaml
