### ISSUE TITLE
Govern the CLI pod to not let it scale above 1

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-operator#510]
Govern the CLI pod to not let it scale above 1

**Comment by kaczyns** [comment]
The operator should probably add owned `Deployment` objects to its list of watches, and re-apply them as necessary.  We will need to be careful that we don't run into a situation like with the `DeploymentConfig` where the `spec.image` or whatever was getting changed by whatever watches the `DeploymentConfig` instances, and then we were changing it back when we noticed.
