### ISSUE TITLE
Display stack status `active` or `inactive`

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-operator#512]
It will be good to display status of stacks for the `Status` field. It should match what kabanero CLI will show in the list.

```
# oc get stacks
NAME                AGE   STATUS
java-microprofile   36m
java-openliberty    36m
java-spring-boot2   36m
nodejs              36m
nodejs-express      36m
nodejs-loopback     36m
svt-springboot      45h
```

**Comment by kaczyns** [comment]
@mtamboli this becomes sort of tricky... there are now multiple versions of the stack behind each `Stack` CR instance.  Having a true/false status like we had for the `Collection` CR instance is sort of misleading.  There's also no easy way for us to tell kubernetes to iterate over the versions of the stack and construct some sort of aggregate, and then display the result.

We could have the operator construct a new field that might look something like this:  
`[ 0.2.5: active, 0.2.6: active, 0.2.7: inactive ]`
and display that instead.... would that be OK with you?

**Comment by mtamboli** [comment]
@kaczyns That seems very useful to me as user. So with this `oc get stacks` will give me a list of all stacks and the versions each one of them and their status.

**Comment by kaczyns** [comment]
OK very good.  We will try to get it in to 0.7.0.

**Comment by dacleyra** [comment]
merged, closing
