### ISSUE TITLE
Consider filtering pipelines archive/yaml to only tekton.dev resources

### ISSUE THREAD

**Issue by dacleyra** [kabanero-io/kabanero-operator#513]
When we process a pipelines tar.gz or yaml file, should we eliminate any resources that are not tekton.dev (Piplines, Tasks, etc)? 
We only watch and reconcile these types of resources.
Security consideration? 

Or do we expect that additional resources types may be included, although they will not be watched and reconciled.

@stephenkinder

**Comment by stephenkinder** [comment]
@dacleyra It seems like we should constrain the configuration to known pipeline CRD kinds.  As you suggest, likely some sneaky security issues if we do not validate.

**Comment by kaczyns** [comment]
This was fixed in #598
