### ISSUE TITLE
Move up to latest Openshift Pipelines 0.10.x patch release

### ISSUE THREAD

**Issue by marikaj123** [kabanero-io/kabanero-operator#523]

**Comment by marikaj123** [comment]
@anneqm - what are the recommended versions of openshift pipelines operator / triggers release for Kabanero release 0.7.0?

**Comment by anneqm** [comment]
@marikaj123 as of now, there are no new Openshift releases of the pipeline and/or  triggers to move up to.  I do see that openshift-pipelines-operator  has a 0.10.6 and a 0.10.7 release available at https://github.com/openshift/tektoncd-pipeline-operator/releases. Quay has those versions as well: https://quay.io/repository/openshift-pipeline/openshift-pipelines-operator?tag=v0.10.7&tab=tags.  These should still be based on Tekton Pipelines 0.10.1 and Tekton Triggers 0.2.1. 

@kaczyns Is there any reason to move up from the openshift-pipelines-operator 0.10.4 to one of the newer ones? I'm not aware of a reason to move up at this time.

**Comment by kaczyns** [comment]
if it's really just a patch release (ie 0.10.z to 0.10.z') then we would just move up for the sake of getting bug fixes.  I'll take a look and see if anything fundamental changed.

**Comment by kaczyns** [comment]
I've asked @dacleyra to take a look at moving up to the latest patch release for Kabanero 0.8.0.

**Comment by kaczyns** [comment]
#570 is merged, I am closing this issue.
