### ISSUE TITLE
Assess move to Tekton Dashboard 0.5.3 for Kabanero release 0.8.0

### ISSUE THREAD

**Issue by marikaj123** [kabanero-io/kabanero-operator#524]
Moving to the appropriate Tekton versions

**Comment by marikaj123** [comment]
@anneqm - What are the recommended version of Tekton Dashbhoard and Webhook Extension for Kabanero 0.7.0?

**Comment by kaczyns** [comment]
@marikaj123 I think it is too late for 0.7.0 to be asking this question, there are only 7 business days left in the release.  We need to be having this conversation in the first couple of days of the release, or perhaps we can have the conversation now for Kabanero 0.8.0.

**Comment by anneqm** [comment]
@marikaj123 @kaczyns for Kabanero 0.7, we'll stay on Dashboards and Webhooks Extension 0.5.2. Please update the releases tag to v0.8.0 for to move up to tekton dashboard and webhook extension 0.6.x?  Thank you!

**Comment by kaczyns** [comment]
@marikaj123 @anneqm I am going to update this issue to reflect that it's for Kabanero release 0.8.0.  During the first two weeks of that release we'll assess the current available version of the Dashboard (0.6.x) and whether its required Openshift Pipelines Operator release is available, and make a decision on whether we are going to move up during the Kabanero 0.8.0 release.

**Comment by marikaj123** [comment]
According to Anne, in the next iteration, the Tekton team is planning to release Dashboard 0.5.3  in with support for Triggers 0.3.1. 
For Kabanero release 0.7.0, we will keep the existing levels used by Kabanero 0.6.0.

**Comment by kaczyns** [comment]
For Kabanero 0.8.0 we will attempt to move up to dashboard release 0.5.3, which is available now, and works with the version of pipelines and triggers that Kabanero currently uses.
https://github.com/tektoncd/dashboard/releases/tag/v0.5.3
