### ISSUE TITLE
Upgrade to 0.6.0 fails with no matches for kind \"CheCluster\" 

### ISSUE THREAD

**Issue by jgawor** [kabanero-io/kabanero-operator#540]
```
{"level":"info","ts":1582940767.3948023,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"kabaneroplatform-controller","source":"kind source: org.eclipse.che/v1, Kind=CheCluster"}
{"level":"error","ts":1582940772.7410898,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"CheCluster.org.eclipse.che","error":"no matches for kind \"CheCluster\" in version \"org.eclipse.che/v1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/source/source.go:88\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Watch\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:122\ngithub.com/kabanero-io/kabanero-operator/pkg/controller/kabaneroplatform.watchCRWInstance\n\tsrc/github.com/kabanero-io/kabanero-operator/pkg/controller/kabaneroplatform/codereadyworkspaces.go:148\ngithub.com/kabanero-io/kabanero-operator/pkg/controller/kabaneroplatform.add\n\tsrc/github.com/kabanero-io/kabanero-operator/pkg/controller/kabaneroplatform/kabaneroplatform_controller.go:104\ngithub.com/kabanero-io/kabanero-operator/pkg/controller/kabaneroplatform.Add\n\tsrc/github.com/kabanero-io/kabanero-operator/pkg/controller/kabaneroplatform/kabaneroplatform_controller.go:54\ngithub.com/kabanero-io/kabanero-operator/pkg/controller.AddToManager\n\tsrc/github.com/kabanero-io/kabanero-operator/pkg/controller/controller.go:13\nmain.main\n\tsrc/github.com/kabanero-io/kabanero-operator/cmd/manager/main.go:177\nruntime.main\n\t/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/proc.go:200"}
{"level":"error","ts":1582940772.7413206,"logger":"cmd","msg":"","error":"Unable set a watch for the codeready-workspaces instance. Error: no matches for kind \"CheCluster\" in version \"org.eclipse.che/v1\". Codeready-workspaces instance: &{map[apiVersion:org.eclipse.che/v1 kind:CheCluster]}","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\tsrc/github.com/kabanero-io/kabanero-operator/cmd/manager/main.go:178\nruntime.main\n\t/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/proc.go:200"}
```

**Comment by jgawor** [comment]
This happened because I didn't have CodeReady operator installed. So, it seems like a dependency definition is missing somewhere to indicate a prereq on CodeReady. Otherwise, the operator keep crashing and csv status keeps switching between "succeeded" and "installing"

**Comment by kaczyns** [comment]
@jgawor Kabanero requires the CodeReady operator.  Are you suggesting that the CodeReady operator should be optional?

**Comment by jgawor** [comment]
Isn't there some way for an operator to specify what dependencies it has? Meaning, the install of the operator should be end up in a pending or failed state if the dependencies are not met. Right now, they are not specified and the operator keep crashing and the csv state keep changing "installing" and "succeeded" states.

**Comment by dacleyra** [comment]
The CSV can specify required APIs, yes. However, we found that when OLM processes the dependency during install, that it may select an operator in the wrong catalog. So we've avoided adding a lot of those APIs to the required field in the CSV. It may be worth testing to see if OLM is better behaved at this point.

**Comment by kaczyns** [comment]
that isn't going to help here... we get the kabanero operator from our own catalog.  If we require `CheCluster`, then OLM is going to try to:
1) pull it from our own catalog (it doesn't exist there)
2) pull it from some other catalog, undefined behavior

Since both the Che operator in community-operators, and the CodeReady Workspaces operator in redhat-operators, both own that CRD, you could get either one.  Since we want the behavior to be deterministic, we have to install it ourselves.  If you use the install script, it will get installed.  If you don't, then there's no way to have OLM fail the install because the requirements are not met.  It will just pick something.  And since we want it to be deterministic, we don't specify anything.

**Comment by marikaj123** [comment]
According to Jarek, this issue is not for 0.6.0.

**Comment by kaczyns** [comment]
@jgawor Is there anything for us to fix here, at this point?  There is no way for the operator CSV to declare a requirement on CodeReady Workspaces without introducing non-deterministic behavior.  If you'd like CodeReady to be optional, then we can modify the operator to handle the case where the CheCluster CRD is not present.  Please let us know, or close the issue if nothing further is required.

**Comment by jgawor** [comment]
@kaczyns not at this point i guess. not unless OLM deals with prereqs correctly. although, it wouldn't hurt to update https://github.com/kabanero-io/kabanero-operator#deploy-prerequisite-operators.

**Comment by kaczyns** [comment]
That is a good point - there are several other updates that need to be made to the readme as well.  I'll leave this issue open until that work is complete.
