### ISSUE TITLE
Kabanero install doesn't allow specification of landing image

### ISSUE THREAD

**Issue by plainchanter** [kabanero-io/kabanero-operator#541]
I am experimenting with a new platform, and I am able to build all the kabanero-operator images and install them EXCEPT for landing.  The tag for the landing page container is fixed and not specifiable in the install scripting:

Pulling image "kabanero/landing:0.5.0"

**Comment by kaczyns** [comment]
@plainchanter This was fixed in #542.  Please re-build on this level (or cherry-pick the commit from #542 into your branch) to get the updates.

Your Kabanero CR will have this new section (snippet):
```yaml
spec:
  landing:
    image: your/repository:tag
```
