### ISSUE TITLE
Add ability to get/list secrets to the CLI services pod

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#544]
The CLI service needs to get/list secrets so that it can read the PAT required to retrieve resources from protected github and/or GHE releases.  This is similar to how the operator does the same.

In `config/orchestrations/cli-services/0.1/kabanero-cli.yaml`, need to edit the role `kabanero-cli` and add the ability to get and list secrets.

@davco01a FYI

**Comment by jgawor** [comment]
Does that mean we will need to replicate the functionality to read indexes using different protocols to CLI service written in Java?

**Comment by davco01a** [comment]
depending how the stack hub index is configured in the Kabanero CR...yes

If it's configured as GHE stack hub index (with those special tags) the Kabanero CLI has to be capable of performing the additional authentication.

**Comment by jgawor** [comment]
this is where it probably would be good to build a library of the go code so that java code can reuse instead of re-implementing the logic (with its own bugs) into java. or re-implement the java piece in go :)
