### ISSUE TITLE
Kabanero namespace left hanging in terminating state

### ISSUE THREAD

**Issue by maysunfaisal** [kabanero-io/kabanero-operator#564]
I installed a Kabanero 0.6.0 operator from https://github.com/kabanero-io/kabanero-operator/releases and deployed Codeready for playing around with Codewind. If you're curious, you can refer to docs https://kabanero.io/docs/ref/general/installation/installing-codeready-and-codewind.html on how to do this.

When I was done with the namespace, I wanted to take down Codeready. So I just went ahead and deleted the namespace like `oc delete project kabanero` but it was left in a terminating state. 
```
# kubectl get ns kabanero
NAME       STATUS        AGE
kabanero   Terminating   19d
```

I made sure no Kube resources were holding the deletion back with `oc get all -n kabanero`
```
# oc get all -n kabanero
No resources found.
```

Is there a way to list all the CRDs that the kabanero operator is using, to see what is holding the deletion of the namespace? 

FWIW my Kabanero resource says
```
# oc get kabanero -n kabanero
NAME       AGE       VERSION   READY
kabanero   19d       0.6.0     False
```

**Comment by kaczyns** [comment]
Hi @maysunfaisal - in general, just deleting a project is a bad idea.  Some of the objects in there may have finalizers, that some other object removes.  If the object that removes the finalizer stops before the object with the finalizer, then you are stuck doing manual cleanup.

In this case, it's probably the `kabanero` instance that's holding things up.  It requires the `kabanero-operator` pod to remove its finalizer.  You can do `oc get kabanero -n kabanero -o yaml` and check the `metadata` section for any finalizers.  If there are any there, you can delete them using `oc edit`, deleting the finalizers section, and then saving.

The namespace should go away after that's gone.  If it doesn't, you could look at the yaml for the namespace and see if it has a finalizer too:  `oc get namespace kabanero -o yaml`.  

For the future, please delete your Kabanero CR instances before you delete the project.  Or use the `uninstall.sh` script for the kabanero-operator.

**Comment by kaczyns** [comment]
@maysunfaisal I am going to close this issue - please re-open if you continue to have trouble with the uninstall script.  Thanks!
