### ISSUE TITLE
Deploy Appsody and Open Liberty operators v0.4.0

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#567]

**Comment by arthurdm** [comment]
fyi @kaczyns - Appsody Operator's 0.4.0 version is now certified and available in the embedded OperatorHub.

**Comment by kaczyns** [comment]
@arthurdm do the Appsody and Liberty operators need to go together, or can we move Appsody independently of Liberty?

**Comment by arthurdm** [comment]
you can move them independently of each other.

**Comment by dacleyra** [comment]
PR for appsody-operator is up
Do not see OL 0.4.0 in the certified catalog yet

**Comment by arthurdm** [comment]
I have uploaded the OL 0.4.0 artifacts into Red Hat's certification portal, but it's taking a few hours to complete the scan.  I am hoping by tomorrow morning it's completed.

**Comment by arthurdm** [comment]
All cleared now.  

<img width="189" alt="Screen Shot 2020-03-31 at 3 33 53 PM" src="https://user-images.githubusercontent.com/5042215/78067640-1043ee80-7365-11ea-922a-ef1740b74179.png">

**Comment by kaczyns** [comment]
Fixed in #600
