### ISSUE TITLE
Move up to CodeReady Workspaces 2.1

### ISSUE THREAD

**Issue by rtaniwa** [kabanero-io/kabanero-operator#569]
CRW 2.1 will be coming out later this month (March) or the next. We should pull this in to one of the upcoming Kabanero releases feeding into our next version of CP4A.

**Comment by kaczyns** [comment]
@rtaniwa I am a little confused about how we pick this up.  IIRC the CodeReady Workspaces operator offers two channels - `latest` and `previous`.  So, when the `latest` channel changes to use CRW 2.1, Kabanero will pick it up implicitly.  There is nothing that I'm aware of that Kabanero can do to control the version, other than switch channels (from `latest` to `previous`).

Is there something else that we need to do here?

**Comment by rtaniwa** [comment]
Hey @kaczyns . I will need @johnmcollier to weigh in on the mechanics. I just opened this as SteveK mentioned on a call he needed us to evaluate if it would make sense to pick up a new version of CRW for the 2Q release, and we confirmed CRW 2.1 will be available soon and would make sense to use. If there is no work to be done, then that is a bonus.

**Comment by johnmcollier** [comment]
If the latest channel will ensure CRW 2.1 (or really any latest new version) gets pulled in when available, then I think we're fine here.

**Comment by kaczyns** [comment]
OK great - I am going to close this issue.  Please re-open if you discover something that we missed.  Thanks!
