### ISSUE TITLE
Implement an admission webhook in the Kabanero Operator

### ISSUE THREAD

**Issue by kyleschlosser** [kabanero-io/kabanero-operator#57]
We have several actions which can only occur in an admission webhook: 

* Defaulting of resource values
* Ensuring only one instance of Kabanero in a given namespace context
* Setting the relational reference between a collection and a Kabanero instance

The controller runtime supports [admission webhooks](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/webhook) which requires that you implement a handler for the admission action. 

**TLS**
Since a webhook introduces an HTTP listener endpoint, this should be secured with TLS which will require valid certificates be generated. If other examples cannot be found, I would suggest looking at how this was done in the Service Catalog project.

**Comment by bbrowning** [comment]
Note that you cannot use admission webhooks reliably with CRDs unless you only have a single API version of that CRD installed in the cluster at a time. You'll have to drop either the v1alpha1 or v1beta1 version and only go with one. Or, you'll have to upgrade to Kubernetes 1.13.10 or newer (which means OpenShift 4.1 and not 3.11).

**Comment by bbrowning** [comment]
See https://github.com/kubernetes/kubernetes/issues/73752 for the background here. This is fixed in K8s 1.14 and was backported to K8s 1.13.10. It was rejected for backports to K8s 1.12 or 1.11 because they are EOL'd. And the fix is definitely not in OKD 3.11.

**Comment by kaczyns** [comment]
See https://github.com/kabanero-io/kabanero-operator/tree/master/vendor/sigs.k8s.io/controller-runtime/example for an example of how to create a webhook.  The controller-runtime godoc that Kyle references above has more information about how to handle certificates.  It is likely that #288 will require the admission webhook to enforce the relationship between `spec.version` and `spec.versions[0]` in the Kabanero CRD.
