### ISSUE TITLE
Consider separation of lifecycle concerns with the collection controller

### ISSUE THREAD

**Issue by kyleschlosser** [kabanero-io/kabanero-operator#58]
One of the philosophical points of view with the operator pattern is that the operator has a separate lifecycle from the software it manages. This lets you upgrade the operator without disturbing and of the existing software instances, and lets the operator orchestrate roll forward/roll back of a software instance. 

The Kabanero instance controller adheres to this point of view, but the collection controller seemingly violates this point of view. We might consider factoring the collection controller off into another deployment at some point in the future.

**Comment by kaczyns** [comment]
My two cents on this.... I have been lumping the Kabanero controller and the Collection controller into one logical instance.  The Kabanero controller has logic that knows how to read an index.yaml and create `Collection` objects.  The Collection controller has logic that pulls the Kubernetes resources for a collection and creates the object instances (Pipelines, Tasks, etc).  They both sort of work in tandem - I can't imagine a situation where you would want to have one version of the Kabanero controller, but a different version of the Collection controller.

When I think about the two as a logical instance though, I can see the appeal of having a separate operator that manages versions of those two things together.  For example, having a new Kubernetes group `operator.kabanero.io` that contained an object called `Instance` which described which version of the kabanero/colleciton controller to get, and the URL for an index.  Someone would be able to use the operator to deploy a `Kabanero` instance which understood a v2 index.yaml in one namespace, and then another `Kabanero` instance which understood a v3 index.yaml in another namespace, but only have the actual operator installed one time.  The operator would pull one version of the controllers for one namespace, but another version of the controllers for the other.  The Kabanero operator might react to a new Instance by creating a `Kabanero` object in the namespace, and creating two `Deployment` objects, one containing a Kabanero controller at the requested level, and one containing the Collection controller at the same level.  Or perhaps one Deployment that contains both controllers.

On the other hand, the `operator.kabanero.io` group would really just contain the install logic for Kabanero.  All of the so-called "day 2" operations would be managed by the controllers.  I was thinking about new CRD types, for example a CRD that represented a refresh request (go look at the index and refresh/reconcile the contents, as the CLI would do).  However doing so would require the `Kabanero` instance to go look, which is handled by the Kabanero controller, so it would really be the Kabanero controller owning that CRD, not the operator.  Maybe that's enough - the operator controls versioning of the controllers, and the controllers handle everything else.

**Comment by kaczyns** [comment]
The changes being proposed in #288 will likely require this.  It would be good if we could have a new `main()` for the collective controller, and a new Docker container, but continue to source it from the kabanero-operator project (this project) in GitHub.  

We should build a 0.3.0 collection-controller which retains its current behavior.  When we release the 0.4.0 operator, we can include this container in the 0.3.0 version, so that when deploying 0.3.0 kabanero using the 0.4.0 operator, the user will get the 0.3.0 collection controller behavior.  Then, for 0.4.0 and beyond, we'll build a new collection controller container at each release.
