### ISSUE TITLE
Consider including Tekton release w/ dashboard fix for init container failure displays in Kabanero 0.9.0

### ISSUE THREAD

**Issue by bconey** [kabanero-io/kabanero-operator#597]
The Tekton community has put in a fix for the Tekton issue https://github.com/tektoncd/dashboard/issues/1155 with the following comment:
"Ensure we display details of init container failures in the
TaskRun and PipelineRun details pages, to aid users in
debugging failures (often related to missing / misconfigured
secrets, etc.)"

So this update should be included when a new release of the "Tekton Dashboard and WebHooks Extensions" is available. This is the associated release page https://github.com/tektoncd/dashboard/releases

Could Kabanero pick up the new release of the "Tekton Dashboard and WebHooks Extensions" with this fix for the 0.9.0 release?

**Comment by marikaj123** [comment]
Tekton will contain the fix and become available after Kabanero 0.8.0.

**Comment by marikaj123** [comment]
@anneqm - Any update of this fix and what Tecton release will contain it would be appreciated.

**Comment by anneqm** [comment]
@marikaj123 This fix, https://github.com/tektoncd/dashboard/issues/1155, was included in the Tekton Dashboard v 0.6.0 so it is ready for when kabanero moves up to Dashboard v0.6.1.

**Comment by marikaj123** [comment]
@bconey - FYI: the fix was provided in Tekton release 0.6.0 and above https://github.com/tektoncd/dashboard/releases.

**Comment by kaczyns** [comment]
I am closing this, as we've picked up dashboard release 0.6.1 in Kabanero 0.9.0.
