### ISSUE TITLE
Implement digest checking in the collection event loop

### ISSUE THREAD

**Issue by kyleschlosser** [kabanero-io/kabanero-operator#60]
The collections controller is a minimal implementation which when applied retrieves the remote contents and applies these contents. Any modification of the resource results in re-execution of this logic. 

Digest data is available in the remote repository for both the collection as well as the individual resources. The digest for either one or both of these should be recorded in the status, and then application of the collection be limited to the case where the digest is new. 

There is an additional case where the digests changing which may lead to re-application of the collection. This is a bit like "SNAPSHOTS" in a Maven repository, where the HEAD of the repository is changing but the version is not fully committed. This probably should not be supported as a base case, but perhaps could be recognized when a Kabanero instance configuration attribute is present. If no resolution on this is made within the current issue, we should fork this into a separate issue.

**Comment by kaczyns** [comment]
The collection status was updated with the active digest, and logic to avoid re-applying the resource if the digest had not changed, in #76.  There is still the outstanding issue of whether we should attempt to apply the YAML if the digest is not correct (the computed digest on the resource does not match what is in the collection.yaml file).  I've opened #88 to track this, and I don't think it's required to close epic #66, however I don't feel strongly about this so if someone disagrees, please put #88 into epic #66.
