### ISSUE TITLE
Kabanero 0.8.0-rc.1 does not install on a new OCP cluster

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#610]
Fails at the appsody operator install step, see https://github.com/appsody/appsody-operator/issues/251.

**Comment by marikaj123** [comment]
Appsody Team is working on the fix which will be included in the next Appsody Appsody Operator release v0.5.0 which is targeted towards late April.

**Comment by marikaj123** [comment]
Appsody operator team suggested the following workaround solution:
"Knative the issue happens when serving.knative.dev/v1alpha1  group is there but not the Service CRD".
