### ISSUE TITLE
Start installing service mesh from the red hat catalog.

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#613]
Even though Kabanero isn't currently using service mesh, we expect to need it again in a future release.  Lets make the following changes:
* Install from the redhat-operators catalog, and remove it from the kabanero catalog
* It shouldn't be necessary to manually install Elasticsearch, Kiali and Jaeger anymore, since OLM now prefers to install things from the catalog where the requiring operator comes from.  We can just install Service Mesh, and let the dependencies come.  (I hope.  I'm not sure what happens if one of the dependencies fails to install.  I suppose if we are worried about that we can just keep installing them manually).

Kabanero doesn't currently configure service mesh, and it should continue to not configure service mesh.

**Comment by dacleyra** [comment]
https://docs.openshift.com/container-platform/4.3/service_mesh/service_mesh_install/installing-ossm.html#ossm-operatorhub-install_installing-ossm

> Starting with Red Hat OpenShift Service Mesh 1.1.0, you must install the Elasticsearch Operator, the Jaeger Operator, and the Kiali Operator before the Red Hat OpenShift Service Mesh Operator can install the control plane.


I doubt the OLM issues are worked out yet, and as such they've adopted the same procedure we take.
