### ISSUE TITLE
Install openshift pipelines operator 0.11.0 and Tekton Triggers v0.4.0. in Kabanero 0.9.0

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#615]
The openshift pipelines operator 0.11.x is not available yet, but is supposed to contain the "beta" tekton CRDs.  The Kabanero operator needs to pull the openshift pipelines operator 0.11.x into the kabanero-catalog, once it is available in community-operators.  

For a realistic chance of completing this change in 0.9.0, and giving the kabanero pipelines team time to react to the breaking changes in this release, this should be complete by April 20th.

@tseelbach @kvijai82 FYI.

**Comment by kaczyns** [comment]
There will also be a supporting release of the Tekton dashboard here.

**Comment by anneqm** [comment]
openshift-pipelines-operator appears to now be available for v0.11... https://quay.io/repository/openshift-pipeline/openshift-pipelines-operator?tag=v0.11.0&tab=tags

**Comment by kaczyns** [comment]
This has already been discussed offline but I'm including it here for anyone who was not able to follow along.... the image in Quay is not what we are waiting for to pull in the openshift pipelines operator.  The operator must be pushed to community-operators:
https://github.com/operator-framework/community-operators/tree/master/community-operators/openshift-pipelines-operator

**Comment by kaczyns** [comment]
There is a PR out there in community-operators now for this:
https://github.com/operator-framework/community-operators/pull/1563

**Comment by anneqm** [comment]
Note the [openshift-pipelines-operator](https://github.com/operator-framework/community-operators/tree/master/community-operators/openshift-pipelines-operator) has the v0.11.0 that we have been waiting for. This should include Tekton Pipelines v0.11.1 and Tekton Triggers v0.4.0.

**Comment by marikaj123** [comment]
@kaczyns The complete Link:
 https://github.com/operator-framework/community-operators/tree/master/community-operators/openshift-pipelines-operator/0.11.0

**Comment by anneqm** [comment]
Just noticed that v0.11.1 is now available. https://github.com/operator-framework/community-operators/tree/master/community-operators/openshift-pipelines-operator/0.11.1

**Comment by kaczyns** [comment]
We've moved up to 0.11.1.  There is still an outstanding issue that we have with the dashboard 0.6.1 release.  The namespace the dashboard is installed to changed from `tekton-pipelines` to `openshift-pipelines`.  While we acknowledge that `openshift-pipelines` is probably the correct place for the dashboard to be, the Kabanero runtime expects the dashboard to be in `tekton-pipelines`.

We're going to modify the Kabanero install script to install the dashboard to `tekton-pipelines` for the time being.

**Comment by kaczyns** [comment]
The dashboard namespace is changed - I am closing this issue.
