### ISSUE TITLE
upgrade Tekton Pipelines to beta v0.11.0

### ISSUE THREAD

**Issue by tseelbach** [kabanero-io/kabanero-operator#618]
Tekton beta pre-release is available with v0.11.0-release candidate 4. This will be the last RC before the beta release is declared this week. Please see release notes for the changes, deprecation notices, and backward incompatibilities.
https://github.com/tektoncd/pipeline/releases.

**Comment by tseelbach** [comment]
related Pipeline issue:  https://github.com/kabanero-io/kabanero-pipelines/issues/283

**Comment by marikaj123** [comment]
@tseelbach - https://github.com/operator-framework/community-operators/tree/master/community-operators/openshift-pipelines-operator/0.11.0

**Comment by marikaj123** [comment]
Closing the issue since the pipeline was updated to use the Tektone pipeline beta release.
