### ISSUE TITLE
Option to not check sha256 when reading .yaml file for pipeline

### ISSUE THREAD

**Issue by mchenggit** [kabanero-io/kabanero-operator#622]
Currently when supplying a .yaml file for a pipeline release, the kabanero operator is still trying to check for sha256. It should at least have an option to stop checking for the sha256 when the content is a .yaml file.

**Comment by marikaj123** [comment]
@mchenggit - Is there a particular release this is needed by?

**Comment by mchenggit** [comment]
@marikaj123 I can work around it, but fixing it definitely helps improve pipeline development experience.

**Comment by kaczyns** [comment]
This is fixed by #627 and will be available in the first 0.9.0 alpha or rc release.
