### ISSUE TITLE
Support query string in a pipeline url

### ISSUE THREAD

**Issue by mchenggit** [kabanero-io/kabanero-operator#623]
The operator does not support a pipeline URL with a qury string. For example, here is an error message from a stack:

url: https://github.com/mchenggit/kabanero-pipelines/blob/issue267v3/ci/assets/eventing-kabanero-pipelines.tar.gz?raw=true
    status: active
    statusMessage: Can not decode file type of file for Pipeline . Must be .tar.gz
      or .yaml.
    version: 0.2.10

**Comment by marikaj123** [comment]
@mchenggit - Is there a particular release this is needed by?

**Comment by mchenggit** [comment]
@marikaj123 I can work around it, but fixing it definitely helps improves pipeline development experience.

**Comment by kaczyns** [comment]
This is fixed by #625 and will be available in the first 0.9.0 alpha or rc release.
