### ISSUE TITLE
Need to trust default ingress certificate

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#638]
In addition to being able to trust certificates signed by well-known CAs (such as those presented by sites like github.com), the operator will need to be able to trust the OpenShift default ingress certificate.  When the stack hub is hosted locally, it is likely that the certificate it presents to clients is the default ingress certificate, and if the operator trusts this, it does not need to disable certificate verification checking for all hosts.

We may also wish to consider trusting the CA that generates service serving certificates (if we don't trust this already).

**Comment by kaczyns** [comment]
According to kabanero-io/roadmap#155 the default ingress CA can be obtained by getting the secret named `router-ca` in the `openshift-ingress-operator` namespace, and extracting the `.data.tls.crt` from the secret.  It's probably base 64 encoded.  We'll need to figure out either how to mount that secret in the pods that we have, and pass that file name to the HTTP transport, or, just obtain the secret and pass the certificate programmatically.

**Comment by brianxjx** [comment]
does this help?
https://docs.openshift.com/container-platform/4.3/authentication/certificates/service-serving-certificate.html

**Comment by kaczyns** [comment]
@brianxjx no that's for service serving certificates, this is the default ingress certificate.

**Comment by jgawor** [comment]
The ingress certificate should already be in  /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt

**Comment by kaczyns** [comment]
I would have thought something named `service-ca.crt` was the service serving certificate CA.  Are these the same thing?

**Comment by jgawor** [comment]
Sorry, I meant, /var/run/secrets/kubernetes.io/serviceaccount/ca.crt which is used when authenticating against kube api service within the cluster.

**Comment by dacleyra** [comment]
Is there a reason to point the operator at the ingress address and not the internal service address?

**Comment by kaczyns** [comment]
@dacleyra I've been trying to get an answer to that question but no one seems to be able to speak to why some products chose to expose the external route vs the internal service host name.  

With the infrastructure in place in the operator it should be fairly easy to switch out or add a CA to the list that we trust.
