### ISSUE TITLE
Assess move to Tekton Dashboard 0.6.1 for Kabanero release 0.9.0 

### ISSUE THREAD

**Issue by marikaj123** [kabanero-io/kabanero-operator#639]
Move to Tekton Dashboard 0.6.1

**Comment by anneqm** [comment]
@marikaj123 @kaczyns Latest Tekton Dashboard and webhook extension is ready ... https://github.com/tektoncd/dashboard/releases/tag/v0.6.1

**Comment by marikaj123** [comment]
@anneqm - Thanks!

**Comment by dacleyra** [comment]
Resolved by https://github.com/kabanero-io/kabanero-operator/pull/643
