### ISSUE TITLE
Document RBAC kinds required for different use cases

### ISSUE THREAD

**Issue by kyleschlosser** [kabanero-io/kabanero-operator#64]
We need to document that someone who is working with collections (activating, upgrading, etc) will require RBAC authority to create/modify the kind `Collection`. Likewise, someone wanting to configure a Kabanero instance will need access to the Kind `Kabanero`.

**Comment by mingcyu** [comment]
@kyleschlosser Kyle, is this still needed or has it been covered with existing doc?

**Comment by kaczyns** [comment]
@mingcyu WRT Kind `Collection`, I believe we've decided that these should be manipulated either by the Kab operator directly, or with the Kabanero CLI (which uses a Git login).  I don't think any documentation is required for this part.

WRT Kind `Kabanero`, I believe the install instructions say to run as `cluster-admin`.  However there's no reason why this step could not be done as someone with a lower level of access.  I can update this as I go thru the documentation for 0.3.0.  Please leave this open for now.

**Comment by mingcyu** [comment]
@kaczyns Hi Tim, so for the second paragraph do you require ID support/resources to review?  If so can you point us to where you might be working?

**Comment by kaczyns** [comment]
@mingcyu I'm working in kabanero-io/docs#194
