### ISSUE TITLE
Fix the kabanero operator yaml when you run `oc get pod -n kabanero -o yaml`

### ISSUE THREAD

**Issue by StringCheeseCR** [kabanero-io/kabanero-operator#644]
When you run `oc get pod -n kabanero -o yaml` the alm-examples for Kabanero comes out as a string instead of proper yaml.

alm-examples: "[\n  {\n    \"apiVersion\": \"kabanero.io/v1alpha2\",\n    \"kind\":
        \"Kabanero\",\n    \"metadata\": {\n      \"name\": \"kabanero\"\n    },\n
        \   \"spec\": {\n      \"version\": \"0.8.0\",\n      \"stacks\": {\n        \"repositories\":
        [\n          {\n            \"name\": \"incubator\",\n            \"https\":
        {\n              \"url\": \"https://github.com/kabanero-io/kabanero-stack-hub/releases/download/0.8.0-rc1/kabanero-stack-hub-index.yaml\"\n
        \           }\n          }\n        ],\n        \"pipelines\": [\n          {\n
        \           \"id\": \"default\",\n            \"sha256\": \"653e5c69abcefdaf7ac9ef3b826376edb8517f64aca44d5eda40a74ff1d62ee5\",\n
        \           \"https\": {\n              \"url\": \"https://github.com/kabanero-io/kabanero-pipelines/releases/download/0.8.0-rc.1/default-kabanero-pipelines.tar.gz\"\n
        \           }\n          }\n        ]\n      }\n    }\n  },\n  {\n    \"apiVersion\":
        \"kabanero.io/v1alpha1\",\n    \"kind\": \"Collection\",\n    \"metadata\":
        {\n      \"name\": \"java-microprofile\"\n    },\n    \"spec\": {\n      \"version\":
        \"0.2.11\",\n      \"name\": \"java-microprofile\",\n      \"desiredState\":
        \"inactive\"\n    }\n  },\n  {\n    \"apiVersion\": \"kabanero.io/v1alpha2\",\n
        \   \"kind\": \"Stack\",\n    \"metadata\": {\n      \"name\": \"java-microprofile\"\n
        \   },\n    \"spec\": {\n      \"name\": \"java-microprofile\",\n      \"versions\":
        [\n        { \"version\": \"0.2.26\",\n          \"pipelines\": [\n            {
        \"id\": \"default\",\n              \"sha256\": \"653e5c69abcefdaf7ac9ef3b826376edb8517f64aca44d5eda40a74ff1d62ee5\",\n
        \             \"https\": {\n                \"url\": \"https://github.com/kabanero-io/kabanero-pipelines/releases/download/0.8.0-rc.1/default-kabanero-pipelines.tar.gz\"\n
        \             }\n            }\n          ],\n          \"images\": [\n            {
        \"id\": \"java-microprofile\",\n              \"image\": \"docker.io/kabanerobeta/java-microprofile:0.2.26\"\n
        \           }\n          ]\n        }\n      ] \n    }\n  }\n]"

Example of proper alm-examples from codeready-workspaces...
      alm-examples: |-
        [
          {
            "apiVersion": "org.eclipse.che/v1",
            "kind": "CheCluster",
            "metadata": {
               "name":"codeready-workspaces"
            },
            "spec": {
               "server": {
                  "cheImageTag": "",
                  "cheFlavor":"codeready",
                  "devfileRegistryImage": "",
                  "pluginRegistryImage": "",
                  "tlsSupport": true,
                  "selfSignedCert": false
               },
               "database": {
                  "externalDb": false,
                  "chePostgresHostName": "",
                  "chePostgresPort": "",
                  "chePostgresUser": "",
                  "chePostgresPassword": "",
                  "chePostgresDb": ""
               },
               "auth": {
                  "openShiftoAuth": true,
                  "identityProviderImage": "",
                  "externalIdentityProvider": false,
                  "identityProviderURL": "",
                  "identityProviderRealm": "",
                  "identityProviderClientId": ""
               },
               "storage": {
                  "pvcStrategy": "per-workspace",
                  "pvcClaimSize": "1Gi",
                  "preCreateSubPaths": true
               }
            }
          }
        ]

**Comment by kaczyns** [comment]
There is nothing we can do about this - operator lifecycle manager generates this from the CSV, which requires it to be specified as JSON.  You could open an issue in github.com/operator-framework/operator-lifecycle-manager if you'd like to see something different here.
