### ISSUE TITLE
Similar set up for TLS certs for CLI Service as was done for Landing page

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-operator#645]
Need Similar set up for TLS certs for CLI Service as was done for Landing page

see:

 https://github.com/kabanero-io/kabanero-operator/issues/178

  and 

https://github.com/kabanero-io/kabanero-operator/pull/586/files

**Comment by tseelbach** [comment]
The following PR / Issue was also necessary / part of the change to certs for Landing and CLI Service:
 https://github.com/kabanero-io/kabanero-operator/pull/680
https://github.com/kabanero-io/kabanero-operator/issues/674
