### ISSUE TITLE
Consistent labeling for deployments

### ISSUE THREAD

**Issue by justinflemingibm** [kabanero-io/kabanero-operator#660]
Currently there is not consistent labeling across the various deployments created by the kabanero operator. 

Can we get a label added to each deployment created so we can select everything deployed by kabanero?

As an example, these are the labels use for the kappnav deployments:
```
app.kubernetes.io/component=kappnav-was-controller,
app.kubernetes.io/instance=kappnav,
app.kubernetes.io/managed-by=kappnav-operator,
app.kubernetes.io/name=kappnav
```

**Comment by kaczyns** [comment]
The labels that we want to apply are defined here:
https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels

**Comment by kaczyns** [comment]
My initial thoughts on how to reconcile the instance name (as opposed to just the name) are this:
* The operator deployment itself has no instance name.  OLM deploys this.
* The Kabanero CR will be given an instance name (not sure how this would work but it seems like the mutating webhook could pick out some part of the UUID, or something, to use as the instance ID)
* The instance ID from the Kabanero CR instance would then be propagated downstream to any resources created by the Kabanero controller.  This includes Stack CR instances, and resources created by the stacks.  

It's important that there is only a single Kabanero CR instance allowed per namespace, and that we don't try to give each Stack CR a unique instance name.  Since multiple Stack CRs can share Pipeline and Task instances, it would be difficult to manage which labels to use for these objects.

**Comment by dacleyra** [comment]
@justinflemingibm do you want labels on just the deployments/pods, or are services and any other particular objects necessary?

**Comment by justinflemingibm** [comment]
I think deployments is the minimum, but maybe it's worth adding them to other resources as well if it's not a lot of extra work. I don't think we would look for them on anything other than deployments at the moment though

**Comment by kaczyns** [comment]
this was merged with #668

**Comment by justinflemingibm** [comment]
I was just doing a validation of the new labels that were added for kabanero 0.9.0-rc.3. I didn't realize in the original PR that the labels were only in the deployment template.

The way that I am patching deployments is by selecting deployments by label. Most of the deployments for kabanero don't have any labels at all:

```
ibmadmin@test-ubuntu:~/git/icpa-install/scripts/common$ oc get deploy -n kabanero --show-labels
NAME                                      READY   UP-TO-DATE   AVAILABLE   AGE     LABELS
codeready-operator                        1/1     1            1           4h42m   olm.deployment-spec-hash=c5774c865,olm.owner.kind=ClusterServiceVersion,olm.owner.namespace=kabanero,olm.owner=crwoperator.v2.1.1
events-operator                           1/1     1            1           4h36m   <none>
icpa-landing                              1/1     1            1           4h39m   app=icpa-landing
kabanero-cli                              1/1     1            1           4h36m   <none>
kabanero-operator                         1/1     1            1           4h41m   olm.deployment-spec-hash=9774fb49d,olm.owner.kind=ClusterServiceVersion,olm.owner.namespace=kabanero,olm.owner=kabanero-operator.v0.9.0
kabanero-operator-admission-webhook       1/1     1            1           4h37m   <none>
kabanero-operator-collection-controller   1/1     1            1           4h36m   <none>
kabanero-operator-stack-controller        1/1     1            1           4h36m   <none>
```

What are the chances that we could at least get the `app.kubernetes.io/part-of=kabanero` added to all of the deployments that kabanero directly creates in 0.9.0?

**Comment by dacleyra** [comment]
I don't think I can do anything about the kabanero-operator Deployment

OLM does not appear to allow setting metadata.labels for the operator Deployment
It only provides DeploymentSpec to set in the CSV
https://github.com/operator-framework/operator-lifecycle-manager/blob/release-4.3/pkg/api/apis/operators/v1alpha1/clusterserviceversion_types.go#L62

As far as I can tell, when the Deployment is built, it only adds the olm ownership labels
https://github.com/operator-framework/operator-lifecycle-manager/blob/release-4.3/pkg/controller/install/deployment.go#L84

**Comment by dacleyra** [comment]
merged, closing
