### ISSUE TITLE
Allow service accounts, roles,  and role bindings and Digest substitution for pipelines and event listeners

### ISSUE THREAD

**Issue by mchenggit** [kabanero-io/kabanero-operator#661]
As we move eventlistener to kabanero namespace, we also need to move the service account, roles, role bindings that it runs under.  If we allow them to be packaged together with the pipeline zip, with Digest substitution, we will have a way to version and evolve them as well. This eliminates the need to create a global service account, role, role binding for all event listeners.

As an example of what to move, currently, 
the service account is tekton-webhooks-extension-eventlistener
The role is: tekton-webhooks-extension-minimal
The role binding is: tekton-webhooks-extension-minimal

We will construct a new example, but with a new role that does not need any create/delete options.

**Comment by kaczyns** [comment]
For Kabanero 0.9.0 we are going to ship a static service account / role / binding for the event listeners to use.
