### ISSUE TITLE
Collection controller always overrides repositories with default

### ISSUE THREAD

**Issue by kyleschlosser** [kabanero-io/kabanero-operator#68]
There is no if checking in the collection controller, so it always loads from the default: 

https://github.com/kabanero-io/kabanero-operator/blob/2881b937b2a26e7b55fa855c6a0402c9eb908c90/pkg/controller/collection/collection_controller.go#L157

Add an "if ! nil" to prevent this

**Comment by stephenkinder** [comment]
@tspewak thanks for looking into this quickly.  With this bug fix allow the operator to override the default collection to point at an alternate collection?

**Comment by tspewak** [comment]
I think it will.

**Comment by kaczyns** [comment]
Closing as fixed by #74
