### ISSUE TITLE
Move to Appsody and Open Liberty Operator 0.6.0 for Kabanero release 0.10.0

### ISSUE THREAD

**Issue by marikaj123** [kabanero-io/kabanero-operator#683]
Move up to a new Operator

**Comment by jgawor** [comment]
@marikaj123 is this for 0.9?

**Comment by kaczyns** [comment]
@jgawor Marika added the 0.10.0 release so I don't think it's for 0.9.0.  I don't think the Appsody or OL operators 0.6.0 are available yet, so I've added the `blockedBy-Appsody` label as well.

**Comment by jgawor** [comment]
Ok. Thanks. I don't see the targeted release information from regular GitHub issue.

**Comment by marikaj123** [comment]
@jgawor - I am preparing for Kabanero release 0.10.0. Appsody operator will become available later in May after the GM date of Kabanero 0.9.0.

**Comment by dacleyra** [comment]
merged, closing
