### ISSUE TITLE
Update the release 0.0.2 deployment data

### ISSUE THREAD

**Issue by kyleschlosser** [kabanero-io/kabanero-operator#69]
Update the artifact https://github.com/kabanero-io/kabanero-operator/releases/download/0.0.2/kabanero-operators.yaml

to:
* use the kabanero-operator:0.0.2 tag instead of latest
* use the proper namespacing

Then reattach the update to the release and notify other team members (such as doc)

**Comment by mezarin** [comment]
Done.
