### ISSUE TITLE
Suppress warning messages on governance for invalid stacks

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-operator#700]
After enabling OAuth for landing page, I see that governance policy is displayed. But it is showing below warning about active stacks which does not relevant to me and taking too much attention of the user. Talked to @dacleyra and he thinks that operator might be able suppress them.

![image](https://user-images.githubusercontent.com/29490950/81429772-4c205f80-912c-11ea-8b31-f2a26e572365.png)

**Comment by dacleyra** [comment]
I thought this might be from stack status generated by operator, but it looks like it is landing's message. They may be doing a compare without checking active state.
