### ISSUE TITLE
Move to Tekton Dashboard 0.6.x for Kabanero 0.9.0

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#706]
We are waiting for two fixes:
* https://github.com/tektoncd/dashboard/issues/1367
* Another fix and I can't find an issue for it

This will go into 0.9.0 when it's ready.  It will either be dashboard 0.6.1.2 or 0.6.2, whatever they decide to name it.

**Comment by anneqm** [comment]
Includes fix for https://github.com/tektoncd/dashboard/issues/1255.

**Comment by anneqm** [comment]
release is here.. this includes fix for one security issue..  https://github.com/tektoncd/dashboard/releases/tag/v0.6.1.3..

**Comment by marikaj123** [comment]
Kabanero has included  https://github.com/tektoncd/dashboard/releases/tag/v0.6.1.3..
