### ISSUE TITLE
Add sso to full.yaml

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-operator#713]
Kabanero has a way to enable RedHat SSO using [Configuring Kabanero with Red Hat Single Sign On (RH-SSO)] (https://kabanero.io/docs/ref/general/configuration/rhsso.html) . When I looked at the full.yaml in the Kabanero 0.9.0, it does not have the sso fields.I had to add this to the kabanero instance to enable it.
```
sso:
   adminSecretName: rhsso-secret
   enable: true
```

**Comment by dacleyra** [comment]
merged, closing
