### ISSUE TITLE
Error handing when there is an error with pipelines

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-operator#724]
User can update piplelines release in the kabanero instance. But if you have any error like incorrect SHA value, there is not error on Kabanero instance or stacks. The only symptom is that the pipelines do not show up. Can this be made more easy to debug by operator throwing this error?

**Comment by dacleyra** [comment]
```
Status:
  Summary:  [ 0.2.12: active ]
  Versions:
    Images:
      Digest:
        Activation:  d45808722cb8fe7f27280887e3c2e22faf19a24630fe428111280266bc15764f
      Id:            Open Liberty
      Image:         docker.io/appsody/java-openliberty
    Pipelines:
      Digest:  1348e90cc3269b6e65837f71011bef6f0dc662781a41442cb5ce3714cb91b890
      Git Release:
      Name:          default
      URL:           https://github.com/kabanero-io/kabanero-pipelines/releases/download/0.9.0/default-kabanero-pipelines.tar.gz
    Status:          active
    Status Message:  Index checksum: 1348e90cc3269b6e65837f71011bef6f0dc662781a41442cb5ce3714cb91b890 not match download checksum: 63b98242b60f6a1cf240b430d24659b9727d16013935553a798be1e6c122c479 for Pipeline Name default
    Version:         0.2.12
Events:              <none>
```

We set the status message, but we're not setting error state. Will look into setting the state.

**Comment by dacleyra** [comment]
On master
- If I change the sha in the gitops section, the Kabanero instance becomes Ready=False
- If I change the sha in the stacks section, the Stack becomes Error

I believe this is working as intended, and with the right status feedback now

**Comment by mtamboli** [comment]
Thank you @dacleyra for fixing and verifying!
