### ISSUE TITLE
Update Service, Create Configmap or Update CRD for Certificate for new GO rest service

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-operator#766]
In order to get a certificate and key injected into pod for the GO rest service it may be necessary
to:

Seems like something like the following has to happen:

1. Gen signed cert and key

2. Define a secret with the cert and key

3. Annotate the service for the GO rest service with the secret

there are a bunch of options here ( @gawor pointed me to this doc ):

https://docs.openshift.com/container-platform/4.4/authentication/certificates/service-serving-certificate.html#add-service-certificate_service-serving-certificate

 with creating config maps, updating CRDs trying to determine which is most appropriate and if the operator should perform these on behalf of the new GO REST service

**Comment by davco01a** [comment]
The genned swagger for the GO service has:

TLSCertificate    flags.Filename `long:"tls-certificate" description:"the certificate to use for secure connections" env:"TLS_CERTIFICATE"`
TLSCertificateKey flags.Filename `long:"tls-key" description:"the private key to use for secure connections" env:"TLS_PRIVATE_KEY"`
TLSCACertificate  flags.Filename `long:"tls-ca" description:"the certificate authority file to be used with mutual tls auth" env:"TLS_CA_CERTIFICATE"`

**Comment by davco01a** [comment]
and:


// build standard config from server options
		if s.TLSCertificate != "" && s.TLSCertificateKey != "" {
			httpsServer.TLSConfig.Certificates = make([]tls.Certificate, 1)
			httpsServer.TLSConfig.Certificates[0], err = tls.LoadX509KeyPair(string(s.TLSCertificate), string(s.TLSCertificateKey))
			if err != nil {
				return err
			}
		}

**Comment by kaczyns** [comment]
The REST service is using openshift oauth sidecar and so the actual container doesn't require a certificate anymore.
