### ISSUE TITLE
RBAC errors in the Kabanero operator log when applying the sample/default collection

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#78]
The following RBAC errors are observed in the operator log when applying the default collection:
```
"error":"serviceaccounts \"appsody-sa\" is forbidden: User \"system:serviceaccount:kabanero:kabanero-operator\" cannot get serviceaccounts in the namespace \"kabanero\": no RBAC policy matched"
```
and
```
"error":"clusterrolebindings.rbac.authorization.k8s.io \"appsody-admin\" is forbidden: User \"system:serviceaccount:kabanero:kabanero-operator\" cannot get clusterrolebindings.rbac.authorization.k8s.io at the cluster scope: no RBAC policy matched"
```
Some consideration is needed as to how much authority the Kabanero operator service account should have, or whether someone should be pre-configuring some of these roles at the cluster scope so that the service account does not need cluster admin authority.

**Comment by kaczyns** [comment]
@smcclem and @kvijai82 and I worked thru a sample development kabanero pipeline today.  To get past the RBAC errors above we added the following permissions to the service account that the operator uses:
get,create,list serviceaccount, persistentvolume, clusterrolebinding
(the pipeline setup included a PV)

This got us most of the way there.  However the cluster role binding turned out to be trying to grant `cluster-admin` authority to the service account running the pipeline, and the Kabanero operator does not have cluster-admin authority and therefore cannot give cluster-admin authority.

We added cluster admin authority to the service account running the Kabanero operator:
```
oc adm policy add-cluster-role-to-user cluster-admin -z kabanero-operator
```

This got us past the last RBAC issue, however it's pretty heavy-handed and now the Kabanero operator has permission to do just about anything.  Some additional thought is needed here.

**Comment by tseelbach** [comment]
consider using RH buildah push instead of docker push to avoid elevated perms for PV

**Comment by kaczyns** [comment]
Yes, I did not use the script and therefore was not aware of the pseudo-requirement that the kabanero-operator service account has cluster admin privileges.  If this is expected at this point, then we should just change the `role.yaml` to have cluster admin privileges and be done with it.

**Comment by stephenkinder** [comment]
So I think for 0.1.1 we should assume kabanero operator has cluster-admin, and we can either work to reduce that authority in the near term future or wait for requirements to reduce it.

**Comment by ralanlittle** [comment]
I agree

**Comment by tspewak** [comment]
script was moved here https://github.com/kabanero-io/kabanero-foundation/blob/master/scripts/install-kabanero-foundation.sh    
release is updated.
KABANERO_BRANCH="${KABANERO_BRANCH:-0.1.0}"
script still has
oc adm policy add-cluster-role-to-user cluster-admin -z kabanero-operator -n ${namespace}
removing the  release-0.1 tag since Steve says we will look into the future.

**Comment by kaczyns** [comment]
I am removing the status red label since this is not targeted for a release and therefore the red label makes no sense.

**Comment by kaczyns** [comment]
The kabanero operator seems firmly entrenched in "cluster admin" mode right now, so I'm going to close this issue and we can re-open it when having cluster admin authority becomes a problem.
