### ISSUE TITLE
Implement status reporting logic in the Kabanero and Collections controllers

### ISSUE THREAD

**Issue by kyleschlosser** [kabanero-io/kabanero-operator#8]
Status reporting seems to be broken for some of the underlying services. Individually test each of the services (Tekton, KNative Eventing, etc) to see that a bad status on those services shows as a bad status on the Kabanero instance.

**Comment by kaczyns** [comment]
@mezarin and I came up with a strategy here.  We're going to look up the `knativeserving` and `knativeeventing` objects in their respective namespaces, and use the condition for `Ready` to determine whether there is a problem.  If there is a problem, there should be a `message` that we can copy to the `Kabanero` object.  If the object does not exist, it means there was a problem installing the knative eventing or serving operator, or some other problem that is preventing the operator from installing the knative eventing or serving code.

**Comment by kyleschlosser** [comment]
Resolved by #111
