### ISSUE TITLE
Kabanero -> Collection reconciliation logic is not clear

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#87]
I am considering the following scenario:
A `Kabanero` instance is created, which points to a repository (index.yaml) containing 3 collections.  Two collections (A and B) are featured, and one (c) is not.  The `Kabanero` instance is deployed with Spec.Collections.enableFeatured set to `true`, so the `Kabanero` instance creates two `Collection` objects, one for A and one for B.  It does not create one for `C` because it is not a featured collection.

Later, someone wants to use collection C and so it is activated manually by creating a `Collection` instance for collection C.

Later still, the Kabanero controller is called to reconcile the `Kabanero` instance.  The expected state is that there is a `Collection` object for the two featured collections, but no `Collection` object for the not featured collection.  However there are three `Collection` objects.

Clearly, the `Collection` object representing collection C should not be deleted, since it was activated manually.  However, it's not clear how the Kabanero controller should determine this.  In the initial reconciliation, the Kabanero controller needs to know that it should create `Collection` objects for A and B, but not for C.  That same reconciliation logic needs to know that later, it might be valid to have A and B and C.  Or, it might be valid for A and B to have been de-activated manually.

Some thoughts I had for how we might come closer to resolving this:
1) The `Collection` object could create a hint indicating that it arrived at its current state due to some manual action.  During `Kabanero` reconciliation, it is OK for these resources to be in a seemingly inconsistent state.  This may require leaving a `Collection` object allocated even when the collection is deactivated (there would need to be a Status field indicating this).  I'm not sure how we would know that a `Collection` arrived at its current state due to a manual action.  It may not be possible.
2) The Kabanero controller could have different logic for its first pass, and then set a marker in its Status that indicates it's been initialized and that further reconcile attempts should not modify the Collection state.
3) Have the `Kabanero` object become the source of the collection state.  When activating a collection, the `Kabanero` Spec is modified somehow to indicate that a particular collection is active.  The Kabanero controller then activates the collection by creating a `Collection` instance (or by removing a `Collection` instance).  I'm not sure if the Spec or the Status section would be more appropriate for this information.

I'd like to hear other thoughts on how to resolve this.  @kyleschlosser @tspewak @stephenkinder 

I'd like to end up in a place where reconciliation logic in either the Kabanero controller or the Collection controller doesn't end up changing the state of one or more Collections in a way that is contrary to manual actions that had been performed previously.

**Comment by kyleschlosser** [comment]
The primary manual actions (at this time) are:
* creation/removal
* updates to the active version

I suggest that the Kabanero instance controller annotates any collections that it creates (in addition to the owner relationship). Then when the Kabanero instance controller executes, it compares the list of featured collections from the repository against the list of featured collections that have the annotation. The instance controller only creates missing collections, it does not remove collections. A side effect is that removing a collection from the featured list in the index will not remove it from any clusters. 

The Kabanero instance controller then does not control the version of the featured collections, only the presence of the featured collections. Some outcomes: 
* Deletion of a featured collection will cause immediate restore of the deleted collection.
* Declaring a new collection as featured in the index will cause it to be installed into various remote clusters
* Removing a collection from the featured list will have no effect
* The collection administrator still controls the version of all collections, even featured collections. They do not, however, control the initial version of the featured collection, that will always be the latest.

**Comment by ianpartridge** [comment]
Aside:

> A Kabanero instance is created, which points to a repository (index.yaml) containing 3 collections. Two collections (A and B) are featured, and one (c) is not.

Does this mean you expect the `index.yaml` to contain a notion of "featured collection"? If so, my team is not aware of that requirement and it's not in our current prototype YAML.

Please either open an issue against `kabanero-collection` or add to the existing issue where we're discussing the format of `index.yaml`.

**Comment by ianpartridge** [comment]
^^ @groeges

**Comment by kaczyns** [comment]
@ianpartridge @groeges there is currently some confusion as to what a featured collection is.  Please see the discussion in our issue #63.  We will sort it out and get back to you.

**Comment by stephenkinder** [comment]
@kaczyns and I decided we could close this issue due to the myriad changes to the collection repo for Kabanero.

When featured/default collections are part of the collection schema, we can look to enhance the operator at that time.
