### ISSUE TITLE
Add support for Che when provisioning a Kabanero Foundation instance

### ISSUE THREAD

**Issue by kyleschlosser** [kabanero-io/kabanero-operator#9]
The inclusion of Che as part of the Kabanero foundation allows enterprises to develop microservices leveraging remote Kubernetes resources.  Additionally, it will be a preparation step for enabling multi-architecture implementations, such as IBM p- and z-architectures.

**Comment by marikaj123** [comment]
Assignee: Melissa and Jay

**Comment by kaczyns** [comment]
My understanding is that this epic needs to move out to the next release (0.3.0) because we are not going to advertise the Che support until the Appsody extension is ready.

**Comment by mingcyu** [comment]
Hi Tim, noted documentation needed but didn't see a documentation work item linked in this epic, are we still looking for documentation assistance for 0.3?

**Comment by kaczyns** [comment]
The operator work for Che integration has completed.
