### ISSUE TITLE
Prepare for Kabanero Operator submission to community operators

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#95]
Get the Kabanero operator into a state where we can decide to push to community_operators when necessary.

All of the dependent operators may not be available in community_operators, therefore testing should be done by building a private registry using `operator_registry`, which contains the versions of the operators we use:
1) openshift-pipelines
2) knative-eventing
3) knative-serving
4) knative-contrib (TBD)
5) appsody

Submission to community_operators requires testing on OpenShift 4.x.  Kabanero will not support 4.x but we can still test that the operator starts up OK there and that a `Kabanero` and associated `Collection` objects are created.  Our private registry may conflict with some of what is already available in the catalog, so some hand-tending may be necessary.  If we are using operators from the catalog, we should be sure that the version is appropriate.  (for example tekton-0.4 and tekton-0.5 have different CRDs)

We should ensure that the Kabanero description displayed in the OpenShift console makes it clear that Istio is required and must be configured manually.  We can link to those instructions.

**Comment by marikaj123** [comment]
Appsody operator Epic needed by Aug 16.

**Comment by bbrowning** [comment]
Note that the Knative Serving and Knative Eventing operators will be moving out of community operators into redhat-operators as well as a repackaging of those operators in the near future.

Also, everything in the community operators repo is expected to work on OpenShift 4 and will show up in every OpenShift 4 console. If Kabanero does not support OpenShift 4 then expect the submission to get rejected. From reading your docs it's not clear that Kabanero is tested on OpenShift 4.

**Comment by marikaj123** [comment]
As per discussion with Diana and Tim, this work was moved out from the Oct-7 release

**Comment by kaczyns** [comment]
We've decided not to publish this operator at community-operators.
