### ISSUE TITLE
Complete local testing defined in community-operators for OpenShift

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#96]
Local testing for community-operators is defined here:
https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md

We should follow the OpenShift 4.x test guidelines, which means we will need to obtain an OpenShift 4.x cluster to use.

The operator will not officially support OpenShift 4.x when we do this, but we can still make sure that it starts and that `Kabanero` and `Collection` objects can be created, and the appropriate pipelines and tasks are available.

We should run `operator-sdk scorecard` and view the results, taking them "with a grain of salt" since the recommendations are not always appropriate.

**Comment by marikaj123** [comment]
Is this for Oct 7?

**Comment by kaczyns** [comment]
We have been carrying this forward and we're going to try to get to it for Oct 7 but it probably won't be done by then.  It's not required by Oct 7.
