### ISSUE TITLE
Review contribution guidelines defined in community-operators

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#97]
The community-operators contribution guidelines are defined here:
https://github.com/operator-framework/community-operators/blob/master/docs/contributing.md

Specifically, we should review the description in the CSV to make sure it addresses what is required in the contribution guidelines, like the manual steps required before installing (Istio).

The package yaml should be reviewed to be sure it's correct.

Running the tools like `operator-sdk` and `operator-courier` to validate will be done in the testing issue, not here.

**Comment by marikaj123** [comment]
Is this for the Oct-7 release?

**Comment by kaczyns** [comment]
We've been carrying this forward and we'll try to get it done by Oct 7 but it probably won't be.  It's not required for Oct 7.

**Comment by kaczyns** [comment]
It's pretty clear that this operator will not be published in community-operators, due to the lack of a "one-click install experience".  There are too many manual steps required before you can install this operator... it's best served by a link to the install instructions at kabanero.io.
