### ISSUE TITLE
Kabanero controller should watch Collection instances it creates

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#99]
Part of the discussion in #87 is how a `Kabanero` instance should ensure that the featured collections remain valid (that there is a `Collection` object behind it).  Today, if you delete a `Collection` object for a featured collection, it is not immediately re-created by the Kabanero controller.  

The Kabanero controller should be able to watch `Collection` objects, and the reconcile process should re-create them if necessary.

**Comment by kaczyns** [comment]
It may make sense to do this concurrently with #134

**Comment by dacleyra** [comment]
This function was delivered
